### PR TITLE
fix(ide): add async DNS check for host.docker.internal in container environments

### LINKED ISSUE #1567: cli cannot link to vscode under code-server(webide) architecture
### What happened?

as title. 

Image

Image

some info: 

Image

### What did you expect to happen?

It is reasonable to say that the ide products of vscode fork can be directly supported here, and it is hoped that the link can be supported here, so that the ide running in the cloud can be better supported.

### Client information

│ 关于 Qwen Code                                                                                  │
│                                                                                                 │
│ CLI 版本                         0.7.2                                                          │
│ Git 提交                         d0fac547                                                       │
│ 模型                             qwen3-coder-plus                                               │
│ 沙箱                             no sandbox                                                     │
│ 操作系统平台                     linux                                                          │
│ 操作系统架构                     x64                                                            │
│ 操作系统版本                     4.19.91-009.ali4000.alios7.x86_64                              │
│ Node.js 版本                     v20.19.0                                                       │
│ NPM 版本                         10.8.2                                                         │
│ 会话 ID                          9fbc62f2-1d8f-4de3-b5bc-719fe484405b                           │
│ 认证方式                         openai                                                         │
│ 基础 URL                         https://idealab.xxxxxx.com/api/openai/v1                  │
│ 内存使用                         236.9 MB                                                       │
│ IDE 客户端                       VS Code                                             

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by yiliang114**
## TLDR

Fix IDE client connection failure in container environments (e.g. code-server / WebIDE) where `host.docker.internal` is not available. The `getIdeServerHost()` function is now async and performs a DNS lookup to verify `host.docker.internal` is resolvable before using it, automatically falling back to `127.0.0.1` when it is not.

### Problem

In Docker Desktop, `host.docker.internal` is automatically configured to resolve to the host machine. However, this hostname may not exist in:

- **Linux Docker** without `--add-host=host.docker.internal:host-gateway`
- **code-server / WebIDE environments** that run inside containers but not via Docker Desktop
- **Other container runtimes** like Podman that may not support this hostname

The previous implementation detected container environments via `/.dockerenv` or `/run/.containerenv` and unconditionally used `host.docker.internal`, causing IDE connection failures in environments where that hostname is unresolvable.

### Changes

1. **Async `getIdeServerHost()`**: Now performs a `dns.lookup` to check if `host.docker.internal` is resolvable before using it
2. **Result caching**: First lookup result is cached in a module-level variable to avoid repeated DNS queries
3. **Debug logging**: Logs DNS check results in container environments to aid troubleshooting
4. **Test helper**: Exported `_resetCachedIdeServerHost()` for test isolation
5. **Comprehensive tests**: Added 6 new test cases covering all scenarios (non-container, container with reachable host, container with unreachable host, Podman container detection, caching behavior, and end-to-end HTTP connection URL verification)

## Reviewer Test Plan

1. Pull the branch and run tests: `npx vitest run packages/core/src/ide/ide-client.test.ts`
2. Verify all 24 tests pass (18 existing + 6 new)
3. (Optional) In a Docker container with `host.docker.internal` configured, verify IDE connects normally
4. (Optional) In a code-server environment without `host.docker.internal`, verify IDE falls back to `127.0.0.1`

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ✅  | ❓  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Fixes #1567

### CODE REVIEW

File: packages/core/src/ide/ide-client.ts [hunk 1]
```diff
@@ -853,8 +855,67 @@ export class IdeClient {
...
+ * 3. Falls back to `127.0.0.1` if the hostname is not reachable.
+ */
+export async function getIdeServerHost(): Promise<string> {
+  if (cachedIdeServerHost !== undefined) {
+    return cachedIdeServerHost;
+  }
+
   const isInContainer =
     fs.existsSync('/.dockerenv') || fs.existsSync('/run/.containerenv');
-  return isInContainer ? 'host.docker.internal' : '127.0.0.1';
```
Comment (yiliang114) [inline packages/core/src/ide/ide-client.ts]: `/run/.containerenv` `/.dockerenv` Whether these two files exist and whether the domain name `host.docker.internal` can be resolved are two things. 

For example, in the server environment of code-server and vscode, they were created by docker instantiation, but there is a high probability that the domain name will not be resolved.
