### PR TITLE
fix(cli): remove residual blank lines after MCP init completes

### LINKED ISSUE #3095: Extra blank line below status bar compared to Claude Code
## Problem

After launching Qwen Code, there are **3 blank lines** below the status bar at the bottom of the terminal. In comparison, Claude Code only has **2 blank lines** below its status bar. This extra blank line wastes vertical screen space and is visually inconsistent with the upstream behavior.

**Claude Code**:

Image

**Qwen Code**:

Image

## Steps to Reproduce

1. Launch Qwen Code in a terminal (`qwen` or `npm run dev`).
2. Observe the blank space below the status bar — there are 3 empty lines.
3. Launch Claude Code (`claude`) in the same terminal for comparison — there are only 2 empty lines below the status bar.

## Expected Behavior

Qwen Code should have the same number of blank lines (2) below the status bar as Claude Code, keeping the layout compact and consistent.

### PR DESCRIPTION
**Pull request by BZ-D**
## Summary

Fixes #3095. During startup `ConfigInitDisplay` rendered a `<Box marginTop={1}>` plus a content line, so Ink's live area grew by 2 rows. When initialization finished (~1s) and the component unmounted, Ink shrank the live area but the rows it had already committed to the terminal scrollback **cannot** be reclaimed — leaving a visible blank gap above the input.

**Root cause (first principles):** any component that appears in the live area at startup and later unmounts will leave residual rows in scrollback, because terminal rows that have scrolled past the live region are physically fixed. The only robust fix is to keep the live area height constant across the init → ready transition.

**Approach:** move the MCP init status into the `Footer`'s left-bottom status slot — `Footer` is always mounted at fixed height, so the init message just occupies the same row as the idle hint (`? for shortcuts`). The status participates in the existing priority chain: `ctrlC / ctrlD / escape / vim / shell / autoAccept / configInit / hint`. Zero layout shift.

## Changes

- New hook `useConfigInitMessage(isConfigInitialized)` — subscribes to `mcp-client-update` and returns a string or `null` (extracted from the deleted component).
- `Composer.tsx`: drop `<ConfigInitDisplay />` and its import.
- `Footer.tsx`: insert `configInitMessage` branch into `leftBottomContent`, rendered with `<GeminiSpinner />` + text.
- Delete `ConfigInitDisplay.tsx`.
- `Footer.test.tsx`: mock `UIState` now sets `isConfigInitialized: true` (otherwise the init branch fires and changes the snapshot).

## Test plan

- [x] `vitest run packages/cli/src/ui/components/Footer` — 8/8 pass
- [x] `vitest run packages/cli/src/ui/components/Composer` — 14/14 pass
- [x] `tsc --noEmit` clean for all touched files
- [ ] Manual: launch CLI with MCP servers configured → observe spinner in footer during init, no blank rows remain after completion
- [ ] Manual: launch CLI with no MCP servers → `Initializing...` briefly in footer, then normal hint

### CODE REVIEW

**Comment by BZ-D** [comment]
## E2E Test Cases

### Config Init Display

image


### Show 2 Lines below after initializing

At most 3 lines including statusline text

image

Footer with two lines:

image


### Display without statusline

First, show 'initializing...':

image

Then, changed to '? for shortcuts':

image

**Comment by BZ-D** [comment]
## 测试报告

### 自动化测试

| 检查项 | 结果 |
|---|---|
| `vitest run Footer.test.tsx` | **11/11 pass** (原 8 + 新增 3) |
| `vitest run Composer.test.tsx` | **14/14 pass** |
| `tsc --noEmit` (touched files) | clean |
| `eslint` (touched files) | clean |
| pre-commit hook (prettier + eslint) | 两次 commit 均通过 |

#### Footer 测试用例

```
✓ renders the component
✓ does not display the working directory or branch name
✓ displays the context percentage
✓ displays the abbreviated context percentage on narrow terminal
✓ status line rendering › renders multi-line status line output
✓ status line rendering › suppresses hint when status line is active
✓ config init message › shows init status in place of the hint while config is initializing   ← 新增
✓ config init message › falls back to the hint once config is initialized                     ← 新增
✓ config init message › stays suppressed when a custom status line is active                   ← 新增（回归）
✓ footer rendering (golden snapshots) › renders complete footer on wide terminal
✓ footer rendering (golden snapshots) › renders complete footer on narrow terminal
```

第 3 条是关键回归测试：防止未来有人把 `configInitMessage` 分支放回 `suppressHint` 之前，导致 custom statusline 场景下再次出现 1 行抖动。

### 盲审覆盖的场景

跑了 8 轮无方向审计，核心不变量「live 区高度跨 `init → ready` 恒定」在以下场景全部成立：

| 场景 | init 期间左下行 | init 完成左下行 | 高度差 |
|---|---|---|---|
| 默认（无 custom statusline） | `⠋ Initializing...` (1 行) | `? for shortcuts` (1 行) | 0 |
| Custom statusline（`suppressHint=true`） | null (0 行) | null (0 行) | 0 |
| ctrl+C / ctrl+D / Esc 按下 | 对应提示 (1 行) | 对应提示 (1 行) | 0 |
| Vim INSERT | `-- INSERT --` (1 行) | `-- INSERT --` (1 行) | 0 |
| Shell mode / AutoAccept | 对应 indicator (1 行) | 对应 indicator (1 行) | 0 |
| Narrow terminal（column 布局） | 内联 spinner+文本 (1 行) | hint (1 行) | 0 |
| Screen reader（走 `ScreenReaderAppLayout`） | 顶层 Footer 展示 init | 顶层 Footer 展示 hint | 0 |
| Dialog 打开期间（auth/theme/editor） | Composer 不渲染 | Composer 不渲染 | 与原组件 parity |

关键验证点：
- `<Text>{null}</Text>` 在 Ink v6 里返回 null、0 行高（`node_modules/ink/build/components/Text.js:13-15` 确认），这是 P1 问题的物理根据。
- `isInputActive` 不依赖 `isConfigInitialized`（`AppContainer.tsx:1220`），InputPrompt/Footer 全程可见。
- `GeminiSpinner`（不带 "Responding" 前缀的那个）不订阅 StreamingContext，init 期间正常转动。
- hook 返回值通过 `isConfigInitialized ? null : message` 同步门控，避免 effect 异步清空 state 造成的 1 帧 flash。
- `mcp-client-update` 事件全仓只有 `useConfigInitMessage` 一个订阅者（新 hook 取代原组件的订阅，无重复监听）。

### 需要人工验证（我无法在 CI/沙盒里做的）

- [x] `npm run start` 启动 CLI，观察启动 ~1s 内 footer 显示 `⠋ Initializing...`，完成后切为 `? for shortcuts`，上方无残留空行
- [x] 配置 MCP servers 后启动，观察 `Connecting to MCP servers... (x/y)` 数字递增
- [ ] 启用 custom statusline 后启动，确认 footer 不显示 init 字样、也不抖动
- [ ] 窄终端（< 80 columns）下重复上述，footer 走 column 布局不应破坏高度恒定性

如需补充其他 case 的覆盖，请在 review 中指出。

File: packages/cli/src/ui/components/Footer.tsx [hunk 1]
```diff
@@ -96,6 +103,10 @@ export const Footer: React.FC = () => {
   ) : showAutoAcceptIndicator !== undefined &&
     showAutoAcceptIndicator !== ApprovalMode.DEFAULT ? (
     <AutoAcceptIndicator approvalMode={showAutoAcceptIndicator} />
+  ) : configInitMessage ? (
```
Comment (BZ-D) [inline packages/cli/src/ui/components/Footer.tsx:107]: Moving the init status into `Footer` regresses screen-reader mode. `Composer` only renders `<Footer />` when `!isScreenReaderEnabled`, while the old `ConfigInitDisplay` was rendered regardless, so users running with a screen reader now lose all MCP init progress feedback during startup. We should keep an accessible path for this message outside the footer gate, or special-case screen-reader mode here.

**Comment by BZ-D** [comment]
## Review

### Overview

Fixes #3095 — extra blank line below the status bar at startup. Root-cause analysis is accurate: `ConfigInitDisplay` occupies 2 rows in the live area at startup; when it unmounts, Ink shrinks the live area but the rows already committed to terminal scrollback are physically fixed and cannot be reclaimed.

**Approach**: move the MCP init status into `Footer`'s `leftBottomContent` slot so it shares the same row as `? for shortcuts`. Since `Footer` has constant height, the live area no longer changes size across the init → ready transition, eliminating the residual rows. Clean direction.

### Code quality

- **Hook extraction is tidy** (`useConfigInitMessage.ts`). Swapping the effect dep from `config` to `isConfigInitialized` avoids unnecessary re-subscriptions. The early `return` plus the "gating on isConfigInitialized" comment is a nice touch — returning `null` rather than clearing state prevents a transient frame that still shows the stale message on the flip to initialized.
- **Priority chain is sensible**: `ctrlC / ctrlD / escape / vim / shell / autoAccept / configInit / hint` — urgent states first, guidance states last.
- **i18n / theming** follow existing conventions (`t()` + `theme.text.secondary`).

### Risks & suggestions

**🟡 1. One-row residual still exists when a custom statusline is active**

The code comment at `Footer.tsx` honestly acknowledges this: when `suppressHint` is true, `leftBottomContent` used to be `null`; now it becomes `configInitMessage` during init and then returns to `null` after — reintroducing the same class of scrollback residual (1 row instead of 2, and only when a custom statusline is configured). Worth considering whether to either (a) skip the init message entirely when `suppressHint`, or (b) render init progress inline with the statusline row. The test comment argues \"strictly better than the original bug\" which holds, but the issue isn't fully eliminated — would be clearer to call this out in the PR description too.

**🟡 2. Vim / Shell / AutoAccept modes mask init status**

`configInit` sits below these in the priority chain. In practice users are unlikely to be in those modes during the ~1s init window, but with auto-enabled modes or `--prompt` flows, init progress becomes invisible. Not a bug, just worth confirming it's intentional.

**🟢 3. Test coverage**

Three new assertions (initializing / initialized / custom statusline) cover the main branches well. Adding `isConfigInitialized: true` to `createMockUIState` defaults is necessary to keep existing snapshots stable — PR description already calls this out. A \"ctrlC still wins over configInit\" assertion isn't strictly needed since the priority chain is covered by existing tests.

**🟢 4. Minor**

Inline `<GeminiSpinner />` inside `<Text>` matches the previous component and renders fine in Ink. `useState` initializer calls `t('Initializing...')` even when gated out — could be lazy, but the cost is negligible.

### Verdict

**LGTM, mergeable.** Root cause is diagnosed correctly and the fix goes after the only physically correct axis (keep live-area height constant). Hook extraction and the gating detail are handled well, and test coverage is adequate. The main caveat is the residual single row in the custom-statusline case, which is already documented in code comments and test comments as an accepted trade-off — a one-line mention in the PR description would make it easier for reviewers to evaluate.

File: packages/cli/src/ui/components/Footer.tsx (hunk 1 above)
Comment (BZ-D) [reply packages/cli/src/ui/components/Footer.tsx:107]: Good catch — the old `ConfigInitDisplay` was rendered in `Composer` outside the `!isScreenReaderEnabled && <Footer />` gate, and moving it into the footer silently dropped the init feedback for screen-reader users.

Fixed in 29838ada0: `Composer` now renders `configInitMessage` as a plain `<Text>` node when `isScreenReaderEnabled` is true, reusing the same `useConfigInitMessage` hook. This keeps the Footer-based rendering (and its constant live-area height) for everyone else — screen-reader users never experienced the residual-blank-line issue that motivated the move in the first place, so an independent text node is harmless for them.

**Review by qqqys — COMMENTED** [review]
## Review

Solid, well-motivated fix. The root-cause framing in the description — that scrollback is append-only so any startup-mounted block leaves residue — is exactly right, and moving into the always-mounted `Footer` slot is the structurally correct solution. A few notes below.

### Works well
- **Hook extraction is clean.** Gating on `isConfigInitialized` *before* returning state (rather than clearing from the effect) avoids a transient frame of the stale "Connecting to MCP servers…" string — nice subtlety, good that it's commented.
- **Lazy `useState(() => t('Initializing...'))`** avoids re-translating each render.
- **Accessibility preserved**: screen-reader users still get the message inline in `Composer` where their reader announces it naturally.
- **`createMockUIState` now defaults `isConfigInitialized: true`** so existing golden snapshots don't flip — good defensive catch.

### Issues / questions

**1. The screen-reader path still has the original bug.**
```tsx
{isScreenReaderEnabled && configInitMessage && (
  <Text>{configInitMessage}</Text>
)}
```
This is still a conditionally-mounted block — when `configInitMessage` flips to `null` it unmounts and leaves a residual row. Smaller (1 row, no `marginTop={1}`) but not zero. The description claims "the only robust fix is constant live-area height", and this branch quietly violates that. Not a blocker for screen-reader users (visual layout matters less), but worth calling out, or keeping a 1-row placeholder post-init for consistency.

**2. Priority-chain ordering vs. `autoAccept`.**
`configInit` sits *after* `showAutoAcceptIndicator`, so a user launched in YOLO / auto-accept-edits will never see the init spinner. The old component rendered regardless of footer state. Is intentional suppression desired here? A one-line rationale comment next to the ordering would help.

**3. Doubled subscription.**
`useConfigInitMessage` is now called in both `Composer` and `Footer`, producing two independent `appEvents.on('mcp-client-update', …)` listeners. Perf-wise negligible (events are rare, ~1s window), just semantically redundant. Not worth restructuring for.

**4. Test coverage gaps.**
- No test for the new `isScreenReaderEnabled && configInitMessage` branch in `Composer`.
- No direct unit test for the `useConfigInitMessage` hook — in particular the `Connecting to MCP servers… (n/total)` path, which is now the only place that string lives.

**5. Manual-test checkboxes still unchecked.**
The two manual verifications in the test plan are exactly what this PR is about — Ink scrollback behavior is invisible to unit tests. Please run them before merge.

### Verdict
Approve-pending on (1) — either acknowledge or fix — and ideally a small hook-level test for the MCP-progress string. Other points are optional.

**Comment by BZ-D** [comment]
Thanks for the thorough review @qqqys — addressed in c4064a627.

**1 & 3 (screen-reader path + doubled subscription).** You were right that the extra branch in `Composer` still had the unmount-residue bug. After manual verification on `--screen-reader`, `ScreenReaderAppLayout` already mounts `<Footer />` directly, so the `Composer` branch was producing a duplicated `Connecting to MCP servers…` line (image below). Removed the branch entirely — the Footer is the single source of truth for init progress in both layouts, which also eliminates the doubled `appEvents` subscription.

screen-reader duplicate line

**2 (priority-chain ordering).** Agreed — suppressing init progress under YOLO / auto-accept-edits was not intentional. Moved `configInitMessage` ahead of `AutoAcceptIndicator` and added a short rationale comment. Approval-mode indicator takes over immediately when init finishes (~1s), so the auto-accept signal isn't lost.

**4 (hook tests).** Added `useConfigInitMessage.test.ts` — 7 cases covering: null-when-initialized, default `Initializing…`, progress strings on `mcp-client-update`, reset-to-default when clients map is empty, flip-to-null on config transition, and unsubscribe on both unmount and transition.

**5 (manual checkboxes).** Manually verified `--screen-reader` mode (see screenshot above) and default mode before and after the changes. Will tick the boxes in the description.

Re (1) specifically: I agree the screen-reader branch as it stood was not constant-height. Dropping it rather than patching it also matches the "Footer is always mounted at fixed height" framing in the description.

**Review by wenshao — APPROVED** [review]
No issues found. LGTM! ✅ _— gpt-5.4 via Qwen Code /review_
