### PR TITLE
fix: replace spawn shell option with explicit shell args to avoid Node.js DEP0190 warning

### LINKED ISSUE #1115: (node:9184) [DEP0190] DeprecationWarning: Passing args to a child process with shell option true
### What happened?

(node:9184) [DEP0190] DeprecationWarning: Passing args to a child process with shell option   │
│   true can lead to security vulnerabilities, as the arguments are not escaped, only              │
│   concatenated.                                                                                  │
│   (Use `node --trace-deprecation ...` to show where the warning was created)

### What did you expect to happen?

(node:9184) [DEP0190] DeprecationWarning: Passing args to a child process with shell option   │
│   true can lead to security vulnerabilities, as the arguments are not escaped, only              │
│   concatenated.                                                                                  │
│   (Use `node --trace-deprecation ...` to show where the warning was created)

### Client information

* **CLI Version:** 0.3.0
* **Git Commit:** c9af7481
* **Model:** coder-model
* **Sandbox:** no sandbox
* **OS Platform:** win32
* **OS Arch:** x64
* **OS Release:** 10.0.19045
* **Node.js Version:** v24.2.0
* **NPM Version:** 11.3.0
* **Session ID:** 1bcb5e56-597c-4a0b-89e2-5ed3a5deb915
* **Auth Method:** qwen-oauth
* **Memory Usage:** 154.1 MB

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by afarber**
## TLDR

Replaces `spawn(command, { shell: true })` and `spawn(command, [], { shell: true })` patterns with explicit `spawn(shell, ['-c', command])` to eliminate Node.js DEP0190 deprecation warning.

## Dive Deeper

Node.js 20+ introduced DEP0190 deprecation warning that triggers when passing an args array to `child_process.spawn()` with `shell: true`. The warning exists because arguments are only space-concatenated, not properly escaped, which can lead to shell injection vulnerabilities.

Before:

```typescript
  spawn(command, [], { shell: true })
  spawn(command, { shell: true })
```

After:

```typescript
  const shell = isWindows ? 'cmd.exe' : 'bash';
  const shellArgs = isWindows ? ['/c', command] : ['-c', command];
  spawn(shell, shellArgs);
```

This pattern was already used in shellExecutionService.ts for PTY spawning, so this PR applies the same approach consistently across all spawn calls.

Files changed:

  - packages/cli/src/utils/handleAutoUpdate.ts - auto-update process spawning
  - packages/cli/src/utils/sandbox.ts - proxy process spawning (macOS seatbelt and Docker)
  - packages/core/src/services/shellExecutionService.ts - shell command execution

## Reviewer Test Plan

1. Run with Node.js 20+ and --pending-deprecation flag to verify no DEP0190 warning appears:
  `NODE_OPTIONS="--pending-deprecation --trace-warnings" npm run start`
2. Execute shell commands via the CLI and verify they work correctly
3. On Windows, verify commands execute properly with cmd.exe /c

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | yes | ❓  | yes |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Fixes #1115

### CODE REVIEW

File: packages/cli/src/utils/handleAutoUpdate.ts [hunk 1]
```diff
@@ -53,7 +54,10 @@ export function handleAutoUpdate(
     '@latest',
     isNightly ? '@nightly' : `@${info.update.latest}`,
   );
-  const updateProcess = spawnFn(updateCommand, { stdio: 'pipe', shell: true });
+  const isWindows = os.platform() === 'win32';
+  const shell = isWindows ? 'cmd.exe' : 'bash';
```
Comment (DennisYu07) [inline packages/cli/src/utils/handleAutoUpdate.ts]: Is this better to use '/bin/sh' instead of 'bash' to avoid some conner case such as in **Alpine** it dose not have bash?
