### PR TITLE
fix(core): handle shell line continuations in command splitting

### LINKED ISSUE #3158: Разрешить выполнение: ''?
### What happened?

Shell cd dev/team/api && \                                                 ←                             │
  │    git add app/Http/Controllers/Web/FileController.php \                                                                  │
  │      resources/views/web/as/ routes/web.php && \                                                                           │
  │    git commit -m "feat: web                               │
  │                                                                                                                                │
  │   cd dev/team/api && \                                                                                      │
  │   git add app/Http/Controllers/Web/ListController.php \                                                                   │
  │      routes/web.php && \                                                                            │
  │   git commit -m "feat: web страница — список" 2>&1                                                             │
  │                                                                                                                                │
  │ Разрешить выполнение: ''?                                      

### What did you expect to happen?

 Shell cd dev/team/api && \                                                 ←                             │
  │    git add app/Http/Controllers/Web/FileController.php \                                                                  │
  │      resources/views/web/as/ routes/web.php && \                                                                           │
  │    git commit -m "feat: web                               │
  │                                                                                                                                │
  │   cd dev/team/api && \                                                                                      │
  │   git add app/Http/Controllers/Web/ListController.php \                                                                   │
  │      routes/web.php && \                                                                            │
  │   git commit -m "feat: web страница — список" 2>&1                                                             │
  │                                                                                                                                │
  │ Разрешить выполнение: ''?                                      

### Client information

Qwen Code: 0.14.3 (55bcec70d)
Среда выполнения: Node.js v25.9.0 / npm 11.6.2
ОС: darwin arm64 (25.4.0)
Аутентификация: Qwen OAuth
Модель: coder-model
Быстрая модель: glm-5
ID сессии: f58690a0-aec6-4468-a5d6-7e80a2382cc8
Песочница: no sandbox
Прокси: no proxy
Использование памяти: 1.40 GB

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by Jerry2003826**
Fixes #3158

## Summary
- Treat shell line continuations (`\` followed by LF) as removed while splitting compound shell commands.
- Keep normal LF/CRLF newlines as command separators, including `\` followed by CRLF, so permission parsing still sees the next command.
- Add regression coverage for multiline chained LF continuations and for the escaped-CRLF safety case.

## Root Cause
`splitCommands()` handled generic backslash escapes before newline and operator splitting. For a command like `cd project && \` followed by LF and `git add`, the segment after `&&` still began with a backslash-newline pair, so command root extraction could resolve to an empty command.

The original PR also treated `\` followed by CRLF as a continuation, but bash does not: the backslash escapes only the carriage return and the following newline still separates commands. The follow-up commit removes that CRLF special case.

## Validation
- `npm run test --workspace=@qwen-code/qwen-code-core -- src/utils/shell-utils.test.ts -t "CRLF|line continuation"`
- `npm run test --workspace=@qwen-code/qwen-code-core -- src/utils/shell-utils.test.ts`
- `npm run lint --workspace=@qwen-code/qwen-code-core`
- `npm run typecheck --workspace=@qwen-code/qwen-code-core`

### CODE REVIEW

File: packages/core/src/utils/shell-utils.ts [hunk 1]
```diff
@@ -224,6 +224,21 @@ export function splitCommands(command: string): string[] {
     const char = command[i];
     const nextChar = command[i + 1];
 
+    if (
```
Comment (wenshao) [inline packages/core/src/utils/shell-utils.ts]: **[Critical]** This treats `\\\r\n` as a shell line continuation, but bash does not: the backslash escapes only the carriage return and the following newline still separates commands. That means an input like `echo SAFE \\\r\nrm -rf /` is parsed as a single `echo` command here, while bash executes the `rm` line separately, so permission checks can miss the second command. Please remove this CRLF-special case, or only normalize CRLF to LF if the execution path also normalizes the command before invoking the shell.

_— gpt-5.5 via Qwen Code /review_

**Review by wenshao — CHANGES_REQUESTED** [review]

File: packages/core/src/utils/shell-utils.ts (hunk 1 above)
Comment (Jerry2003826) [reply packages/core/src/utils/shell-utils.ts]: Thanks for catching this. I removed the CRLF line-continuation special case in `0394d0d` and added regression coverage so backslash + LF is treated as a line continuation while backslash + CRLF still leaves the LF as a command separator.

All CI checks are passing now, including lint, CodeQL, and the macOS/Ubuntu/Windows test matrix. I marked the PR ready for review.

**Review by wenshao — APPROVED** [review]
No issues found. LGTM! ✅ _— gpt-5.5 via Qwen Code /review_
