### PR TITLE
fix: 修复在docker环境中无法连接ide的问题

### LINKED ISSUE #1209: vscode插件已经装好了,但是依旧报错
### What happened?

> /ide install

✕ No installer is available for IDE. Please install the 'Qwen Code Companion' extension manually from the marketplace.

> /ide status

✕ 🔴 Disconnected: IDE connection error. The connection was lost unexpectedly. Please try reconnecting by running /ide enable
  fetch failed

> /ide status

✕ 🔴 Disconnected: IDE connection error. The connection was lost unexpectedly. Please try reconnecting by running /ide enable
  fetch failed

> /bug vscode插件已经装好了,但是依旧报错

Image

### What did you expect to happen?

just try

### Client information

* **CLI 版本:** 4513c113b769e523e4cef59c44f604fa468db8a5
* **Git 提交:** 4513c11
* **模型:** coder-model
* **沙箱:** 0.4.0-2
* **操作系统平台:** linux
* **操作系统架构:** x64
* **操作系统版本:** 6.14.0-36-generic
* **Node.js 版本:** v20.19.6
* **NPM 版本:** 10.8.2
* **会话 ID:** 8ef7b2d5-2dc2-400e-a2bc-f959f443a91c
* **认证方式:** qwen-oauth
* **内存使用:** 240.7 MB
* **IDE 客户端:** IDE

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by BlockHand**
1. Host header verification in the VSCode extension
```bash
app.use((req, res, next) => {
  const host = req.headers.host || '';
  const allowedHosts = [
    `localhost:${this.port}`,
    `127.0.0.1:${this.port}`,
  ];
  if (!allowedHosts.includes(host)) {
    return res.status(403).json({ error: 'Invalid Host header' });
  }
  next();
});
```
2. Host selection logic for CLI clients
```bash
function getIdeServerHost() {
  const isInContainer =
    fs.existsSync('/.dockerenv') || fs.existsSync('/run/.containerenv');
  return isInContainer ? 'host.docker.internal' : '127.0.0.1';
}
```
> When running qwen-code CLI in a Docker container:
- The CLI detects the container environment and uses host.docker.internal as the hostname
- The host header of the sent HTTP request is: host.docker.internal: port number
- However, the VSCode extension only allows localhost: port number and 127.0.0.1: port number
- Therefore, the request is rejected and returns {"error":"Invalid Host header"}

```bash
app.use((req, res, next) => {
  const host = req.headers.host || '';
  const allowedHosts = [
    `localhost:${this.port}`,
    `127.0.0.1:${this.port}`,
    `host.docker.internal:${this.port}`, // 添加Docker支持
  ];
  if (!allowedHosts.includes(host)) {
    return res.status(403).json({ error: 'Invalid Host header' });
  }
  next();
});
```
### Working principle
1. Container detection: CLI determines whether a container is running by checking the /.dockerenv or /run/.containerenv files

2. host selection: If in a container, use host.docker.internal; Otherwise, use 127.0.0.1

3. docker Network: host.docker.internal is a special DNS name provided by docker, pointing to the IP address of the host machine

4. Host header verification: The extension needs to allow this special hostname to pass verification

## Reviewer Test Plan

1. Uninstall the original plugin extension

2. Install new extensions

3. Start docker in the new terminal

4. Run qwen-code to connect to the ide

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | yes  | ❓  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | yes  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs
- Fixes #1209 #984 #1081 #1094 

## Before repair
943DB039-3D73-4C48-BAA8-CD507EC0EF03

https://github.com/user-attachments/assets/75735d50-e84b-4f8b-9ea0-3f84fcf1a69d

## After repair
EDFDD74F-549A-422C-B119-2482D61FEDDC

https://github.com/user-attachments/assets/cd877732-09f4-420b-b0f8-9ee8932dc725

### CODE REVIEW

File: packages/vscode-ide-companion/src/ide-server.ts [hunk 1]
```diff
@@ -164,6 +164,7 @@ export class IDEServer {
         const allowedHosts = [
           `localhost:${this.port}`,
           `127.0.0.1:${this.port}`,
+          `host.docker.internal:${this.port}`, // 添加Docker支持
```
Comment (yiliang114) [inline packages/vscode-ide-companion/src/ide-server.ts]: English comments are better
