### PR TITLE
  fix(cli): reduce terminal redraw cursor movement

### LINKED ISSUE #3144: [BUG] Terminal scroll jumps up/down rapidly during agent execution and response streaming
1 ## Problem Description
      2 
      3 When Qwen Code generates a response (streaming tokens or running agent/plugin execution), the terminal scroll 
        view rapidly jumps between the top and bottom of the buffer. The scroll bar "bounces" up and down ~10-30 times
        per second, making it impossible to read the output.
      4 
      5 This affects **all terminal environments**: SSH sessions, tmux, Proxmox noVNC console, and various terminal 
        emulators.
      6 
      7 ## Root Cause Analysis
      8 
      9 I traced the issue via `strace` and found the root cause in the Ink framework's `log-update` mechanism:
     10 
     11 **What happens on every render (~every 32ms during streaming):**
     12 
     13 1. `log_update.render()` calls `eraseLines(previousLineCount)` to clear the previous UI
     14 2. `eraseLines(N)` generates `\x1B[2K\x1B[1A` repeated N times (clear line + cursor up)
     15 3. For Qwen's typical UI (20-30 lines), this produces: `\x1B[2K\x1B[1A` × 20+
     16 4. Each `\x1B[1A` (Cursor Up) moves the cursor upward → when cursor is at top, terminal **scrolls the entire 
        buffer up**
     17 5. New UI content is written → cursor ends at bottom → terminal **scrolls down**
     18 6. Cycle repeats at 32ms intervals → visible scroll jumping
     19 
     20 **Relevant code path:**
    Ink.onRender() (throttled to 32ms)
      └── log_update.render(output)
            └── stream.write(eraseLines(N) + output)
                  └── eraseLines(N): "\x1B[2K\x1B[1A" × N + "\x1B[G"

     1 
     2 ## Evidence
     3 
     4 `strace` capture of active Qwen process:
    write(17, "\33[2K\33[1A\33[2K\33[1A\33[2K\33[1A... (×20+) ...\33[G
      [~4.8KB of ANSI-colored UI: timer, progress bar, ─── lines, status text]
    ", 4861) = 4861

      1 
      2 This pattern repeats every ~32-100ms during active streaming.
      3 
      4 ## Environment
      5 
      6 | Detail | Value |
      7 |--------|-------|
      8 | Qwen Code version | 0.14.3 |
      9 | Package | @qwen-code/qwen-code |
     10 | Node.js | v20.20.1 |
     11 | OS | Linux (Proxmox VE, Debian-based) |
     12 | Terminal | SSH (OpenSSH), tmux, Proxmox noVNC |
     13 | TERM | xterm |
     14 | Terminal size | 179×44 |
     15 
     16 ## Reproduction Steps
     17 
     18 1. Start Qwen Code: `qwen`
     19 2. Give it a task that involves a long-running agent execution (e.g., Deluge plugin RPC call, file search 
        across many files)
     20 3. Observe terminal scroll bar bouncing rapidly up and down
     21 4. Cannot read output because view keeps jumping
     22 
     23 ## Attempted Workarounds
     24 
     25 | Approach | Result |
     26 |----------|--------|
     27 | `enableLoadingPhrases: false` in settings.json | Reduces one animation, but doesn't fix scrolling during 
        streaming |
     28 | Increasing `throttle(this.onRender, 32)` to `200` | Scrolling still jumps, just less frequently — root cause
        is the `\x1B[1A` pattern, not the rate |
     29 | Removing `eraseLines()` entirely | Eliminates jumping, but old output isn't cleared → screen fills with 
        duplicate content |
     30 | Replacing `eraseLines` with `\x1B[H\x1B[2J` (home+clear) | Clears entire screen including scrollback buffer 
        → loses history, screen flashes |
     31 
     32 ## Suggested Fixes
     33 
     34 ### Option 1: Use alternate screen buffer (recommended)
     35 Switch to `\x1B[?1049h` (alternate screen buffer) for the interactive UI. On exit, `\x1B[?1049l` restores the 
        main buffer. This completely isolates the UI rendering from the scroll buffer — no jumping possible.
     36 
     37 ### Option 2: Delta rendering instead of full re-render
     38 Instead of `eraseLines(N) + fullUI`, only update the lines that actually changed:
     39 - Keep track of which lines changed
     40 - Move cursor to that specific line with `\x1B[<n>A` (limited)

     41 - Only rewrite changed lines
     42 
     43 ### Option 3: Use `\x1B[H` (cursor home) instead of `\x1B[1A` × N
     44 Replace the loop of cursor-up commands with a single "home" command:
    // Instead of: "\x1B[2K\x1B[1A" × 20
    // Use: "\x1B[H" (cursor to row 1, col 1) + "\x1B[J" (clear from cursor to end)

      1 This is **one escape sequence** instead of 40, and doesn't trigger scroll.
      2 
      3 ### Option 4: Add a `--no-fancy-ui` flag
      4 For headless/CI environments, skip the animated UI entirely and use simple line-by-line output (like `curl 
        --progress-bar`).
      5 
      6 ## Related Issues in Other AI CLI Tools
      7 
      8 This is a known problem across all AI CLI agents using Ink:
      9 - GitHub Copilot CLI: https://github.com/github/copilot-cli/issues/1811
     10 - Claude Code: https://github.com/anthropics/claude-code/issues/16939
     11 - Claude Code: https://github.com/anthropics/claude-code/issues/18084
     12 - Claude Code: https://github.com/anthropics/claude-code/issues/34794
     13 
     14 ## Impact
     15 
     16 - **Severity**: High — makes long-running tasks unreadable
     17 - **Frequency**: Every agent execution / streaming response >10 lines
     18 - **Workaround**: None that doesn't break other functionality

    ---

### PR DESCRIPTION
**Pull request by reidliu41**
## TLDR

Summary

This change reduces terminal viewport jumping during interactive streaming output by optimizing the multiline redraw sequence  emitted by Ink/log-update.

Instead of repeatedly writing clear-line + cursor-up for every previous rendered line, the CLI now collapses that exact multiline erase pattern into one relative cursor-up plus erase-down operation.

The optimizer is only installed for interactive TTY output and is skipped for screen reader mode. A compatibility fallback is available via:

  ```bash
  QWEN_CODE_LEGACY_ERASE_LINES=1
```

Changes

  - Add a terminal redraw optimizer for Ink multiline erase sequences.
  - Install it only for interactive TTY sessions.
  - Restore the original stdout writer during cleanup.
  - Add unit tests for optimization behavior, passthrough writes, restore behavior, and fallback disabling.

## Screenshots / Video Demo

Manual Verification

  Ran an interactive streaming prompt with proxy environment variables removed:
```
  timeout 90s script -q -c "\
  stty rows 44 cols 179; \
  env -u NO_COLOR \
    qwen -y -i '请用中文输出30行编号，每行短句。不要调用工具。'" \
  /tmp/qwen-3144-fixed-host-no-proxy-44x179.typescript
```

  Before the fix, the recording contained thousands of repeated cursor-up and clear-line sequences:

  ESC[1A count: 13753
  ESC[2K count: 14756
  max consecutive ESC[1A before one redraw: 37

  After the fix, the old repeated redraw sequence is gone and the output remains complete:

  ESC[1A count: 0
  ESC[2K count: 0
  ESC[2J count: 0
  ESC[H count: 0
  max consecutive old ESC[1A redraw: 0
  output complete: yes

## Testing Matrix

  |          | 🍏  | 🪟  | 🐧 |
  | -------- | --- | --- | -- |
  | npm run  | ❓  | ❓  | ✅ |
  | npx      | ❓  | ❓  | ✅ |
  | Docker   | ❓  | ❓  | ❓ |
  | Podman   | ❓  | -   | -  |
  | Seatbelt | ❓  | -   | -  |

## Linked issues / bugs

  Fixes #3144

### CODE REVIEW

**Review by wenshao — COMMENTED** [review]
Previous review attempt used a stale local base branch and should be ignored. Re-running against the correct remote base now. _— gpt-5.4 via Qwen Code /review_

File: packages/cli/src/ui/utils/terminalRedrawOptimizer.ts [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+    index += search.length;
+  }
+
+  return count;
+}
+
+/**
+ * Ink clears dynamic output via ansi-escapes.eraseLines(), which emits a
+ * clear-line + cursor-up pair for every previous line. That can make terminal
+ * scrollback bounce during frequent streaming renders. Collapse that exact
```
Comment (wenshao) [inline packages/cli/src/ui/utils/terminalRedrawOptimizer.ts]: **[Critical]** This optimization replaces Ink's line-by-line erase sequence with `ESC[n]A + ESC[J`, which clears from the top of the previous frame to the end of the screen, not just the old frame's lines. If anything else writes below the Ink frame between renders (for example async logs or subprocess output), the optimized path can erase unrelated output that the original `eraseLines()` sequence would have left intact.

_— gpt-5.4 via Qwen Code /review_

**Review by wenshao — CHANGES_REQUESTED** [review]

**Comment by reidliu41** [comment]
Good catch, you're right. The ESC[J version widened the erase semantics and could clear unrelated output below the Ink frame.
I've updated the implementation to avoid erase-down entirely. It now clears only the previous frame's lines, preserving Ink's bounded eraseLines() behavior while still avoiding repeated cursor-up operations.
I also added tests covering the no-ESC[J behavior and leaving small/two-line erase sequences unchanged.

File: packages/cli/src/gemini.tsx [hunk 2]
```diff
@@ -155,6 +156,10 @@ export async function startInteractiveUI(
 ) {
   const version = await getCliVersion();
   setWindowTitle(basename(workspaceRoot), settings);
+  const restoreTerminalRedrawOptimizer =
```
Comment (wenshao) [inline packages/cli/src/gemini.tsx:159]: **[Suggestion]** `installTerminalRedrawOptimizer(process.stdout)` is applied before startup finishes, but the restore function is only registered later in `registerCleanup()`. If `render(...)` or another later startup step throws first, `process.stdout.write` stays monkey-patched for the rest of the process.

```suggestion
  const restoreTerminalRedrawOptimizer =
    process.stdout.isTTY && !config.getScreenReader()
      ? installTerminalRedrawOptimizer(process.stdout)
      : () => {};
  try {
```

_— gpt-5.4 via Qwen Code /review_

**Review by wenshao — APPROVED** [review]
Verified against HEAD `5365ceb`:

- The `ESC[J]` erase-down concern is fully addressed — optimizer now emits only `ESC[2K` per line; explicit test asserts `not.toContain('[J')`
- Cursor-position equivalence traced for a 3-line frame: original and optimized sequences both end at top-left with all frame lines cleared
- `cursorUpCount <= 1` early-return keeps small frames untouched (no regression for 1-2 line cases)
- Cleanup path restores original `stdout.write` at unmount with a defensive identity check
- `QWEN_CODE_LEGACY_ERASE_LINES=1` fallback works

Non-blocking nits for later:
- Regex is tightly coupled to `ansi-escapes.eraseLines()` output — worth a brief comment noting the dependency so a future Ink/ansi-escapes change doesn't cause silent degradation
- If Ink ever splits an erase sequence across two `write()` calls, the optimizer won't match; not a concern today since `log-update` renders atomically

LGTM.
