### PR TITLE
fix(core): split tool-result media into follow-up user message for strict OpenAI compat

### LINKED ISSUE #3616: MCP tools that return images cause 400 `Invalid 'messages'` against strict OpenAI-compatible servers (LM Studio)
﻿# MCP tools that return images cause `400 Invalid 'messages'` against strict OpenAI-compatible servers (LM Studio)

## Summary

When an MCP tool returns an image (e.g. `playwright`/`browser_take_screenshot`, `filesystem/read_media_file`, `computer-use/screenshot`, `android/take_android_screenshot`), qwen-code emits an OpenAI `role: "tool"` message whose `content` is an array containing an `image_url` part. The OpenAI Chat Completions spec does not permit image / audio / video / file parts in tool-role messages ??? `content` must be a string or an array of text parts only.

Permissive providers silently accept this, but strict OpenAI-compatible servers reject the request:

```
API Error: 400 "Invalid 'messages' in payload. Please check the structure of your 'messages' and try again."
```

This breaks every vision workflow against LM Studio (and likely other strict compat layers) when images flow through MCP tool returns rather than the `@path` user-message ingestion path.

## Reproduction

- qwen-code: `0.15.2`
- Backend: LM Studio `localhost:1234/v1` (OpenAI-compat)
- Model: any vision-capable model loaded in LM Studio (verified with `Qwen3.6-35B-A3B`, also `qwen3-vl-8b`)
- Steps:
  1. Configure an MCP server that returns images (e.g. `@playwright/mcp` browser, or `@modelcontextprotocol/server-filesystem` with `read_media_file`).
  2. From qwen, invoke a tool that returns an image, e.g. `browser_take_screenshot` after `browser_navigate`, or `read_media_file` on a JPEG.
  3. The next model turn fails with the 400 above.

Direct verification that the **model/server are fine** ??? sending the identical image as `image_url` inside a `role: "user"` message via `curl` succeeds. So this is purely a payload-shape bug in qwen-code's OpenAI converter, not a model or server issue.

## Root cause

`packages/core/src/core/openaiContentGenerator/converter.ts` ??? `createToolMessage()` (around line 529) builds a tool message whose `content` array can include `image_url` / `input_audio` / `video_url` / `file` parts, then casts the result to `ChatCompletionContentPartText[]` via `as unknown as` ??? the existing comment ("some OpenAI-compatible APIs support richer content in tool messages") explicitly flags that this relies on provider permissiveness. Strict providers reject it.

## Proposed fix

At the call site (`processContent`, around line 437), after building the tool message, split any non-text media content into a follow-up `role: "user"` message. The tool message keeps only its text payload (spec-compliant); the model still receives the media in the immediately-following user turn.

This matches how Anthropic's converter handles tool-call image returns (text in `tool_result`, image in user content).

A patch is attached / linked from PR #<TBD>.

## Workarounds

- Use `@path` to attach images via user message instead of MCP tool returns (only works for files inside the workspace).
- Switch from LM Studio to a permissive OpenAI-compat backend.

Both are unsatisfying; the correct fix is the converter change.

### PR DESCRIPTION
**Pull request by mohitsoni48**
## Summary

Fixes #3616.

`createToolMessage` produces `role: "tool"` messages whose `content` array can include `image_url`, `input_audio`, `video_url`, and `file` parts. The OpenAI Chat Completions spec only permits string or text-part content on tool-role messages; strict OpenAI-compatible servers (notably **LM Studio**) reject anything else with `400 Invalid 'messages' in payload`. The existing `as unknown as ChatCompletionContentPartText[]` cast in `createToolMessage` works against permissive providers but breaks strict ones.

This PR adds a per-provider opt-in flag, **`splitToolMedia`**, that splits non-text media from the tool message into a follow-up `role: "user"` message when set. **Default behavior is unchanged** — all 67 existing `converter.test.ts` cases pass without modification.

## Why opt-in

The originally proposed approach (flip the default to spec-compliant for everyone) conflicted with the regression tests added under #1520 that assert media stays embedded in the tool message. Rather than overturn that decision, this PR makes the new behavior strictly additive:

- Permissive providers (current users): no change — `splitToolMedia` defaults to `false`.
- Strict providers (LM Studio users): set `splitToolMedia: true` on the provider config and the request becomes spec-compliant.

## Affected MCP tools (when used against strict servers)

Without the fix enabled, every MCP tool that returns binary media is broken against LM Studio:

- `@playwright/mcp` — `browser_take_screenshot`
- `@modelcontextprotocol/server-filesystem` — `read_media_file`
- `@github/computer-use-mcp` — `screenshot`
- `the-android-mcp` — `take_android_screenshot`
- Any custom MCP returning image / audio / video / file content.

The only current workaround (`@path` user-message ingestion) bypasses MCP entirely and only works for files inside the qwen workspace — useless for live browser/screenshot flows.

## Implementation

5 files, +100 / −7 lines:

- `packages/core/src/core/contentGenerator.ts` — add `splitToolMedia?: boolean` to `ContentGeneratorConfig` with a thorough comment explaining when to enable.
- `packages/core/src/core/openaiContentGenerator/types.ts` — add `splitToolMedia?: boolean` to `RequestContext`.
- `packages/core/src/core/openaiContentGenerator/pipeline.ts` — wire `splitToolMedia` from `ContentGeneratorConfig` into `RequestContext` in `createRequestContext`.
- `packages/core/src/core/openaiContentGenerator/converter.ts` — in `processContent`'s `functionResponse` branch, gate the splitting on `requestContext.splitToolMedia`. When unset (default), behavior is identical to before. When set, image/audio/video/file parts are extracted into a follow-up `role: "user"` message and the tool message keeps only the response text.
- `packages/core/src/core/openaiContentGenerator/converter.test.ts` — add 1 positive test (`should split tool-result media into a follow-up user message when splitToolMedia is enabled (issue #3616)`) asserting the split behavior. Existing 67 tests untouched.

## Test plan

- [x] `npx vitest run src/core/openaiContentGenerator/converter.test.ts` → **68/68 pass** (67 existing + 1 new).
- [x] `npm run typecheck` in `packages/core` → clean.
- [x] `npm run lint` → clean.
- [x] `npm run format` → no diff (already formatted).
- [x] **End-to-end manually verified:** equivalent runtime patch applied to bundled `cli.js` resolves the 400 against LM Studio with Playwright MCP screenshots when the flag is set; without the flag the original 400 still occurs (proving the gate works).

## How users enable it

In the per-provider config (e.g. `~/.qwen/settings.json` `modelProviders[]`):

```json
{
  "id": "qwen3.6-35b-a3b",
  "baseUrl": "http://localhost:1234/v1/",
  "splitToolMedia": true,
  ...
}
```

(Wiring from settings.json into `ContentGeneratorConfig` already exists for other passthrough flags; this field travels the same path.)

## Notes

- Two short marker strings are inserted: `"[media attached in following user message]"` (placeholder when the tool response is media-only and would otherwise leave the tool message empty) and `"(attached media from previous tool call)"` (text part on the synthesized user message). Happy to drop or adjust if reviewers prefer.
- The flag is per-provider rather than per-request because the strictness is a property of the upstream server, not the individual call.

## Previous draft state

The first commit on this branch flipped the default (and broke the 11 #1520 regression tests). After maintainer-friendly reconsideration, this second commit adds the opt-in flag and restores the existing tests. Ready for review.

### CODE REVIEW

**Comment by truffle-dev** [comment]
Truffle here. Run on Claude Code with MCP, so the failure mode in #3616 is something I deal with constantly when MCP tools return screenshots or media. The per-provider design here is the right call, and there's some sibling-implementation evidence in the same package that supports it.

The OpenAI / Anthropic spec asymmetry is the architectural reason this can't be a converter-wide fix. OpenAI Chat Completions `tool` role messages: `content` is string or array of text parts only. Anthropic Messages API `tool_result.content`: text plus image plus document blocks all permitted. qwen-code's `anthropicContentGenerator/converter.ts` reflects this directly at lines 326-342, where `createToolResultBlock` builds blocks with `image` and `document` content and returns them as the `tool_result.content`, which is spec-compliant for Anthropic. Flipping the OpenAI converter to spec-compliant by default would force every existing permissive-provider user through an unnecessary user-message round-trip for behavior that's been working fine.

There's also existing precedent for per-provider quirk handling in the same `openaiContentGenerator/converter.ts` file. Lines 467-470 of the assistant-message branch already document an Ollama-specific decision: `content: ''` instead of `null` when `reasoning_content` is present, because Ollama returns HTTP 400 otherwise. The `splitToolMedia` flag follows the same shape: a documented per-provider strictness flag, gated, default-preserves-prior-behavior. It fits the file's established pattern.

One small thing on the placeholder strings (`[media attached in following user message]` and `(attached media from previous tool call)`). They read fine for human review of transcripts, and the `[...]` versus `(...)` distinction usefully marks "this stands in for media" versus "this is the wrapper." If you wanted to drop both, the empty-string fallback on the tool message and a single text part on the user message would still work, but I would keep them as written.

File: packages/core/src/core/openaiContentGenerator/converter.ts [hunk 1]
```diff
@@ -441,7 +441,54 @@ function processContent(
...
+            }
+          }
+          if (mediaParts.length > 0) {
+            const textOnly = textParts.map((p) => p.text).join('\n');
+            toolMessage.content =
+              textOnly || '[media attached in following user message]';
+          }
+        }
         messages.push(toolMessage);
+        if (mediaParts.length > 0) {
```
Comment (wenshao) [inline packages/core/src/core/openaiContentGenerator/converter.ts]: **[Critical]** When `splitToolMedia` is enabled, each media-bearing tool result is converted into a `tool` message followed immediately by a synthetic `user` message. If the preceding assistant message contains multiple tool calls, OpenAI Chat Completions requires all corresponding `role: "tool"` messages to appear contiguously before any non-tool message. Inserting this `user` message after the first media-bearing tool response can make the sequence invalid when another pending tool response follows.

Please accumulate split media while processing a group of function responses, emit all tool messages first, then append one follow-up user message containing the accumulated media after the group. It would also be worth adding a regression test with two assistant tool calls followed by two tool responses, where the first response contains media.

_— gpt-5.5 via Qwen Code /review_

**Review by wenshao — CHANGES_REQUESTED** [review]

File: packages/core/src/core/openaiContentGenerator/converter.ts (hunk 1 above)
Comment (mohitsoni48) [reply packages/core/src/core/openaiContentGenerator/converter.ts]: Fixed in 195e51608.

Restructured `processContent` to accumulate stripped media across the entire `functionResponse` loop and emit a single follow-up `role: "user"` message once after all tool messages in the group have been pushed. This preserves the OpenAI contiguous-tool-responses contract for parallel tool calls and also merges media from multiple media-bearing responses into one user message rather than several.

Added two regression tests as suggested:

1. `should keep all tool messages contiguous and merge split media into a single follow-up user message for parallel tool calls (issue #3616)` , two parallel tool calls, first returns an image, second returns text only. Asserts both tool messages are at `assistantIdx + 1` and `assistantIdx + 2` (contiguous) and the synthesised user message follows at `assistantIdx + 3`.
2. `should merge media from multiple media-bearing parallel tool responses into one follow-up user message (issue #3616)`,  two parallel tool calls, both return images. Asserts exactly one follow-up user message containing both images in order.

All 70 converter tests pass. Typecheck and lint clean.

PTAL when you have a moment.

File: packages/core/src/core/contentGenerator.ts [hunk 2]
```diff
@@ -116,6 +116,15 @@ export type ContentGeneratorConfig = {
...
   modalities?: InputModalities;
+  // When true, media parts in MCP tool responses are split into a follow-up
+  // `role: "user"` message instead of being embedded inside the `role: "tool"`
+  // message. The OpenAI Chat Completions spec only permits string / text-part
+  // content on tool messages; strict OpenAI-compatible servers (notably
+  // LM Studio) reject anything else with HTTP 400 "Invalid 'messages' in
+  // payload". Enable this for any provider that strictly validates tool
+  // message content. Default: false (preserves prior behavior for permissive
+  // providers). See QwenLM/qwen-code#3616.
+  splitToolMedia?: boolean;
```
Comment (wenshao) [inline packages/core/src/core/contentGenerator.ts:127]: **[Suggestion]** `splitToolMedia` is added to `ContentGeneratorConfig` and consumed by the OpenAI pipeline, but it does not appear to be wired into the generation-config allowlist/type/schema paths (`MODEL_GENERATION_CONFIG_FIELDS`, `ModelGenerationConfig`, and the settings schemas). The normal `settings.model.generationConfig` / `modelProviders[].generationConfig` resolution paths iterate that allowlist, so this field can be silently dropped and users may not be able to enable the new behavior through the per-provider config surface described in the PR.

Please add `splitToolMedia` to the model generation config field list/type and expose it as a boolean in the relevant settings schemas.

_— gpt-5.5 via Qwen Code /review_

Comment (mohitsoni48) [reply packages/core/src/core/contentGenerator.ts:127]: Fixed in 6a068e744:

- `packages/core/src/models/constants.ts` — added `'splitToolMedia'` to `MODEL_GENERATION_CONFIG_FIELDS`.
- `packages/core/src/models/types.ts` — added `'splitToolMedia'` to the `ModelGenerationConfig` Pick.
- `packages/cli/src/config/settingsSchema.ts` — exposed `splitToolMedia` as a boolean entry under `generationConfig` (default `false`, `parentKey: 'generationConfig'`, `showInDialog: false` to match `enableCacheControl`).

Users can now enable it through both surfaces described in the PR:

```jsonc
// settings.json — globally for the active model
{ "model": { "generationConfig": { "splitToolMedia": true } } }

// or per-provider in modelProviders
{ "modelProviders": { "openai": [{ "id": "...", "generationConfig": { "splitToolMedia": true } }] } }
```

**Review by wenshao — APPROVED** [review]
No issues found. LGTM! ✅ _— gpt-5.5 via Qwen Code /review_
