### PR TITLE
fix(core): preserve settings-sourced apiKey when registry model envKey is absent

### LINKED ISSUE #3417: Qwen reports API error each time after restart
### What happened?

Each restart, it reports API Error: 401 Incorrect API key provided.
I need to reenter the API key each time. After that, it works.

### What did you expect to happen?

The API is okay, from bailian. The API key IS stored at the ~/.qwen/settings.json. Somehow qwen doesn't read it.

### Client information

Qwen Code: 0.14.5 (a6612940f)
Runtime: Node.js v22.20.0 / npm 10.9.3
IDE Client: VS Code
OS: linux x64 (6.6.87.2-microsoft-standard-WSL2)
Auth: API Key - openai
Base URL: https://dashscope.aliyuncs.com/compatible-mode/v1
Model: qwen3.5-plus
Fast Model: qwen3.5-plus
Session ID: 3539b3a6-73ba-4aef-b0cf-7064cb4d5bdd
Sandbox: no sandbox
Proxy: no proxy
Memory Usage: 279.0 MB

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by doudouOUC**
## Summary

Fixes #3417

- On restart, `applyResolvedModelDefaults` unconditionally cleared the apiKey resolved from `settings.security.auth.apiKey` (layer 4 fallback) and only read from `process.env[model.envKey]`. When the provider-specific env var was absent, the correctly resolved key was discarded, causing a 401 error.
- Now captures the previously-resolved apiKey before clearing and falls back to it when `process.env[model.envKey]` is empty, but only for safe source kinds (`settings` and general `env` without `via.modelProviders`).
- Added 5 test cases covering: restart fallback, env priority, programmatic key atomicity, cross-model credential safety, and general env var preservation.

## Test plan

- [x] All 50 existing + new tests pass (`npx vitest run packages/core/src/models/modelsConfig.test.ts`)
- [x] Manual: configure `settings.security.auth.apiKey` with a valid key, `modelProviders.openai` with `envKey` pointing to an absent env var, verify no 401 on restart

## 人工验证
```json
  {
    "security": {
      "auth": {
        "selectedType": "openai",
        "apiKey": "你的真实百炼API Key"
      }
    },
    "model": {
      "name": "qwen3.5-plus"
    },
    "modelProviders": {
      "openai": [
        {
          "id": "qwen3.5-plus",
          "name": "qwen3.5-plus",
          "baseUrl": "https://dashscope.aliyuncs.com/compatible-mode/v1",
          "envKey": "NONEXISTENT_TEST_KEY_3417"
        }
      ]
    },
    "$version": 3,
    "general": { "language": "zh" }
  }
```
修复前：
 预期输出：
  缺少 OpenAI 兼容认证的 API 密钥。请设置 'NONEXISTENT_TEST_KEY_3417' 环境变量。
image

修复后：
 预期输出：模型正常返回（如 Hello），无 401 错误。
image

优先级验证
当 envKey 对应的环境变量存在时，应优先使用它而非 settings key：
```bash
  export NONEXISTENT_TEST_KEY_3417="sk-一个错误的key"
  node packages/cli/dist/index.js 'say hello'
```
  预期：报 401（因为用了错误的 env key，而非 settings 中正确的 key），说明环境变量优先级更高。
image

### Test Scenario

Configured `settings.json` with `security.auth.apiKey` set, but `modelProviders.envKey` pointing to a non-existent environment variable:

```json
{
  "security": {
    "auth": {
      "selectedType": "openai",
      "apiKey": "sk-82cd12a8***"
    }
  },
  "model": { "name": "qwen3.5-plus" },
  "modelProviders": {
    "openai": [{
      "id": "qwen3.5-plus",
      "name": "[ModelStudio Standard] qwen3.5-plus",
      "baseUrl": "https://dashscope.aliyuncs.com/compatible-mode/v1",
      "envKey": "NONEXISTENT_TEST_KEY_3417"
    }]
  }
}
```

Environment: `NONEXISTENT_TEST_KEY_3417` is **NOT** set, `DASHSCOPE_API_KEY` is **NOT** set.

---

### Before Fix (fallback branch removed)

```
$ node packages/cli/dist/index.js 'say hello in one word'
缺少 OpenAI 兼容认证的 API 密钥。请设置 'NONEXISTENT_TEST_KEY_3417' 环境变量。
```

The settings-sourced apiKey was unconditionally cleared by `applyResolvedModelDefaults`, and `process.env['NONEXISTENT_TEST_KEY_3417']` was empty, so the key was lost.

### After Fix (with temporary debug log)

```
$ node packages/cli/dist/index.js 'say hello in one word'
[DEBUG-3417] Fallback HIT: preserved apiKey from source=settings, key=***04b1bc
[DEBUG-3417] Fallback HIT: preserved apiKey from source=settings, key=***04b1bc
Hello
```

- Fallback triggered twice (main model + fast model)
- `source=settings` confirms the key was preserved from `security.auth.apiKey`
- Model responded successfully with `Hello` — no 401 error

### Unit Tests

```
$ npx vitest run packages/core/src/models/modelsConfig.test.ts

 ✓ |@qwen-code/qwen-code-core| src/models/modelsConfig.test.ts (51 tests) 8ms

 Test Files  1 passed (1)
      Tests  51 passed (51)
```

All 51 tests pass, including 6 new test cases covering:
1. Settings-sourced apiKey fallback on restart
2. Env var priority over settings apiKey
3. Programmatic apiKey NOT preserved (provider atomicity)
4. Provider-specific env apiKey NOT reused across models
5. General env var (e.g. OPENAI_API_KEY) preservation
6. CLI-sourced apiKey (`--openaiApiKey`) preservation

🤖 Generated with [Qwen Code](https://github.com/QwenLM/qwen-code)

### CODE REVIEW

File: packages/core/src/models/modelsConfig.ts [hunk 1]
```diff
@@ -742,6 +749,23 @@ export class ModelsConfig {
             detail: 'envKey',
           },
         };
+      } else if (
+        previousApiKey &&
```
Comment (wenshao) [inline packages/core/src/models/modelsConfig.ts]: **[Critical]** This fallback can preserve a previous settings/general-env API key across an auth/provider switch. `syncAfterAuthRefresh()` updates `currentAuthType` before applying model defaults, so if the target registry model's provider-specific `envKey` is unset, a key resolved for another provider can be reused for this model's `baseUrl`. That can cause authentication failures and may send credentials to the wrong service.

Please gate this fallback on provider compatibility: for env sources, require the previous env key to be valid for the target auth type; for settings sources, preserve only when the previous auth type is the same or the setting is intentionally provider-agnostic. Otherwise leave `apiKey` unset and let strict provider validation fail.

_— gpt-5.5 via Qwen Code /review_

File: packages/core/src/models/modelsConfig.ts [hunk 2]
```diff
@@ -742,6 +749,23 @@ export class ModelsConfig {
...
+        this.currentAuthType !== AuthType.QWEN_OAUTH &&
```
Comment (wenshao) [inline packages/core/src/models/modelsConfig.ts]: **[Critical]** CLI-sourced API keys are still dropped when the selected registry model has an `envKey` but that environment variable is unset. `resolveCliGenerationConfig` records `--openaiApiKey` as source kind `cli`, but this fallback only preserves `settings` and general `env` sources, so users who explicitly pass a valid CLI key can still lose it during `syncAfterAuthRefresh`.

```suggestion
        (previousApiKeySource?.kind === 'cli' ||
          previousApiKeySource?.kind === 'settings' ||
          (previousApiKeySource?.kind === 'env' && !previousApiKeySource.via))
```

Please also add a regression test for `apiKey: { kind: 'cli', detail: '--openaiApiKey' }` mirroring the new settings/env restart cases.

_— gpt-5.5 via Qwen Code /review_

**Review by wenshao — CHANGES_REQUESTED** [review]

File: packages/core/src/models/modelsConfig.ts (hunk 1 above)
Comment (doudouOUC) [reply packages/core/src/models/modelsConfig.ts]: Thanks for the review. The cross-provider key leak concern is a valid theoretical edge case, but the current safeguards are sufficient for the actual restart scenario this PR targets:

1. Only `settings` (user's global catch-all key) and general `env` (e.g. `OPENAI_API_KEY`, no `via.modelProviders`) sources are preserved — provider-specific env keys are already excluded.
2. `programmatic` sources are excluded to maintain provider atomicity.
3. `syncAfterAuthRefresh` is called with a specific auth type; in practice, auth type doesn't change within the same call.

Adding a full provider-compatibility gate would introduce significant complexity for a marginal safety improvement in an edge case that's unlikely to occur in practice. Not adopting this suggestion.

However, the related comment about CLI-sourced keys (comment below) was valid and has been addressed in b58f171f5.

File: packages/core/src/models/modelsConfig.ts (hunk 2 above)
Comment (doudouOUC) [reply packages/core/src/models/modelsConfig.ts]: Good catch — adopted. 

Added `previousApiKeySource?.kind === 'cli'` to the fallback condition and a regression test for `apiKey: { kind: 'cli', detail: '--openaiApiKey' }`. See b58f171f5.

**Comment by doudouOUC** [comment]
## Manual Verification Report

### Test Scenario

Configured `settings.json` with `security.auth.apiKey` set, but `modelProviders.envKey` pointing to a non-existent environment variable:

```json
{
  "security": {
    "auth": {
      "selectedType": "openai",
      "apiKey": "sk-82cd12a8***"
    }
  },
  "model": { "name": "qwen3.5-plus" },
  "modelProviders": {
    "openai": [{
      "id": "qwen3.5-plus",
      "name": "[ModelStudio Standard] qwen3.5-plus",
      "baseUrl": "https://dashscope.aliyuncs.com/compatible-mode/v1",
      "envKey": "NONEXISTENT_TEST_KEY_3417"
    }]
  }
}
```

Environment: `NONEXISTENT_TEST_KEY_3417` is **NOT** set, `DASHSCOPE_API_KEY` is **NOT** set.

---

### Before Fix (fallback branch removed)

```
$ node packages/cli/dist/index.js 'say hello in one word'
缺少 OpenAI 兼容认证的 API 密钥。请设置 'NONEXISTENT_TEST_KEY_3417' 环境变量。
```

The settings-sourced apiKey was unconditionally cleared by `applyResolvedModelDefaults`, and `process.env['NONEXISTENT_TEST_KEY_3417']` was empty, so the key was lost.

### After Fix (with temporary debug log)

```
$ node packages/cli/dist/index.js 'say hello in one word'
[DEBUG-3417] Fallback HIT: preserved apiKey from source=settings, key=***04b1bc
[DEBUG-3417] Fallback HIT: preserved apiKey from source=settings, key=***04b1bc
Hello
```

- Fallback triggered twice (main model + fast model)
- `source=settings` confirms the key was preserved from `security.auth.apiKey`
- Model responded successfully with `Hello` — no 401 error

### Unit Tests

```
$ npx vitest run packages/core/src/models/modelsConfig.test.ts

 ✓ |@qwen-code/qwen-code-core| src/models/modelsConfig.test.ts (51 tests) 8ms

 Test Files  1 passed (1)
      Tests  51 passed (51)
```

All 51 tests pass, including 6 new test cases covering:
1. Settings-sourced apiKey fallback on restart
2. Env var priority over settings apiKey
3. Programmatic apiKey NOT preserved (provider atomicity)
4. Provider-specific env apiKey NOT reused across models
5. General env var (e.g. OPENAI_API_KEY) preservation
6. CLI-sourced apiKey (`--openaiApiKey`) preservation

🤖 Generated with [Qwen Code](https://github.com/QwenLM/qwen-code)

**Review by wenshao — DISMISSED** [review]
No issues found. LGTM! ✅ _— gpt-5.5 via Qwen Code /review_

**Comment by doudouOUC** [comment]
hi, @tanzhenxin @pomelo-nwu  I will merge this bug fix to main branch. if any issues arise, feel free to contact me.

**Comment by wenshao** [comment]
感谢修复，bug 定位准确，启动场景的 6 个测试覆盖得也扎实。主体方向没问题，但有一个 fallback 分支在跨 provider 切换时会错带 settings-source / cli-source 的 key，建议先处理再合。

## Blocker: same-authType 跨 provider 切换时，settings-source / cli-source 的 key 会被错误保留

触发路径：

1. `modelProviders.openai` 下配两个 provider：`provider-A`（`envKey` 未设 → 启动时 fallback 到 `settings.security.auth.apiKey`，`source.kind === 'settings'`）、`provider-B`（`envKey` 指向另一个未设 env，`baseUrl` 不同，比如 `api.openai.com` vs `dashscope.aliyuncs.com`）。
2. `/model` 切到 `provider-B` → `config.switchModel` → `modelsConfig.switchModel` 在 `modelsConfig.ts:401` 无条件调用 `applyResolvedModelDefaults(model_B)`。
3. 新 fallback 分支（`modelsConfig.ts:752-770`）命中 `previousApiKeySource.kind === 'settings'`，把 A 的 key 塞给 B —— 属于一个服务的 key 会被发到另一个 baseUrl。

测试 case 4（`should NOT preserve env apiKey with via.modelProviders`）只覆盖了 `kind: 'env' + via: modelProviders` 版本；`kind: 'settings'` / `kind: 'cli'` 的对偶用例没覆盖。6 个新测试都是 `syncAfterAuthRefresh(same authType, same modelId)`，没有跨 provider 切换的断言。

## 根因

启动 `isInitialAuth` 场景下，`syncAfterAuthRefresh` Step 1（`modelsConfig.ts:902-911`）在 authType 和 modelId 都没变的情况下仍然命中并调 `applyResolvedModelDefaults`，把 `resolveCliGenerationConfig` 启动时已经正确 resolve 好的 apiKey 冲掉。这个 PR 在 `applyResolvedModelDefaults` 里“清掉再塞回”，但这个方法本身没有“first-time apply 还是真切换”的上下文，只能靠 `source.kind` 猜 —— 而 `settings` / `cli` / 通用 `env`（`!via`）三种 source 在跨 provider 切换时同样会存在、但不该保留。

## 建议修法（二选一）

**A. no-op short-circuit（更干净）**
`syncAfterAuthRefresh` Step 1 命中前先判断：若 `previousAuthType === authType && this._generationConfig.model === modelId`，直接 return。启动场景就走不到 apply 分支，fallback 可以整段删掉。

**B. 调用方传上下文**
给 `applyResolvedModelDefaults` 加参数 `{ allowPreservePreviousKey: boolean }`：
- `syncAfterAuthRefresh` Step 1：`!isAuthTypeChange && 同 modelId` 才传 true
- `syncAfterAuthRefresh` Step 3：false
- `switchModel`（`modelsConfig.ts:401`）：false（明确是切换）
- first-time apply 路径：true

## 必补的测试

```ts
it('should NOT preserve settings-sourced apiKey when switching to a different provider within same authType', ...)
```

场景：`modelProviders.openai` 有 `provider-A` + `provider-B`，启动在 A 上且 `apiKey` source 为 `'settings'`，调用 `switchModel(USE_OPENAI, 'provider-B')`，断言 `gc.apiKey === undefined`。CLI-source (`source.kind === 'cli'`) 的对偶用例也建议补一个。

## 小问题

PR body Summary 段写 “Added 5 test cases”，下面 Tmux Report 段写 “6 new test cases”，diff 里实际 6 个，文字对齐一下。

**Comment by doudouOUC** [comment]
@wenshao 感谢详细的 review，跨 provider key 泄漏的问题分析得很准确。已在 9f470f5 中采纳修改：

## 采纳的方案

综合了你建议的方案 A 和 B 的思路：**将 apiKey 保留逻辑从 `applyResolvedModelDefaults` 移到 `syncAfterAuthRefresh` Step 1**，通过 `isUnchanged`（same authType + same modelId）守卫。

具体做法：
1. **`applyResolvedModelDefaults`** — 完全删除了 `previousApiKey`/`previousApiKeySource` 捕获和 `else if` fallback 分支，恢复为纯净的"清除 → 从 env 读"逻辑。`switchModel` 调用此方法时不会有任何 key 保留行为。
2. **`syncAfterAuthRefresh` Step 1** — 在调用 `applyResolvedModelDefaults` 前后做 save/restore：
   - `isUnchanged = previousAuthType === authType && model === modelId`
   - 仅当 `isUnchanged && apiKey 被清空 && 之前有 savedApiKey` 时恢复
   - 跨 provider 切换（不同 modelId）→ `isUnchanged = false` → 不保留

> 没有用纯 short-circuit（方案 A）的原因：`applyResolvedModelDefaults` 除了处理 apiKey 还会应用 `apiKeyEnvKey`、`samplingParams`、`baseUrl` 等 model registry 配置，这些在构造时并未传入，需要通过此方法补齐。

## 补充的测试

- `should NOT preserve settings-sourced apiKey when switching to a different provider within same authType` — 覆盖 `dashscope → openai` 跨 provider 场景
- `should NOT preserve CLI-sourced apiKey when switching to a different provider within same authType` — CLI source 的对偶用例
- 原 "should NOT preserve programmatic apiKey" 改为正面断言 — same authType + same modelId 下 programmatic key 保留是正确行为（`updateCredentials` 后 `syncAfterAuthRefresh`）

## PR body 数字

已知 summary 段 "5 test cases" 与实际 8 个不一致，下次更新 PR body 时一并修正。

File: packages/core/src/models/modelsConfig.ts [hunk 3]
```diff
@@ -877,7 +877,34 @@ export class ModelsConfig {
...
+          : undefined;
+        const savedApiKeySource = isUnchanged
+          ? this.generationConfigSources['apiKey']
+          : undefined;
+
         this.applyResolvedModelDefaults(resolved);
+
+        // Restore the previously-resolved apiKey if applyResolvedModelDefaults
+        // cleared it (env var not found) and this is the same model.
+        if (isUnchanged && !this._generationConfig.apiKey && savedApiKey) {
```
Comment (wenshao) [inline packages/core/src/models/modelsConfig.ts:916]: **[Critical]** This same-model restore path saves and restores any existing API key source. That includes provider-scoped env keys (`kind: 'env'` with `via.modelProviders`) and `programmatic` keys, even though those are exactly the sources that should not be reused when applying registry provider defaults.

If `process.env[model.envKey]` is removed or rotated before `syncAfterAuthRefresh()` runs for the same model, this can keep using the stale in-memory provider env value. Similarly, a programmatic key can survive provider-default application and be used as if it belonged to the registry model provider. Please gate restoration to the intended restart-safe sources only, for example `cli`, `settings`, or general `env` without `via`, and leave provider-scoped env/programmatic sources unset so strict provider validation can fail.

_— gpt-5.5 via Qwen Code /review_

**Review by wenshao — CHANGES_REQUESTED** [review]
**[Suggestion]** `applyResolvedModelDefaults()` clears `_generationConfig.apiKey` on the non-Qwen-OAuth path, but if no replacement key is found/restored it can leave `generationConfigSources['apiKey']` pointing at the previous source. That makes the effective config and source metadata disagree, which can mislead diagnostics or future source-aware logic. Please clear `generationConfigSources['apiKey']` whenever the effective API key is cleared and no new source is assigned.

_— gpt-5.5 via Qwen Code /review_

File: packages/core/src/models/modelsConfig.ts (hunk 1 above)
Comment (doudouOUC) [reply packages/core/src/models/modelsConfig.ts]: This fallback branch has been entirely removed in 9f470f50d. The apiKey preservation logic was moved to `syncAfterAuthRefresh` Step 1, guarded by `isUnchanged` which checks authType + modelId + envKey + baseUrl. Cross-provider switches (different modelId or different envKey/baseUrl) will NOT preserve the old key.

File: packages/core/src/models/modelsConfig.ts (hunk 2 above)
Comment (doudouOUC) [reply packages/core/src/models/modelsConfig.ts]: This fallback branch has been entirely removed in 9f470f50d. The new save/restore logic in `syncAfterAuthRefresh` is source-kind-agnostic — it preserves the existing apiKey regardless of source kind when `isUnchanged` is true (same authType + modelId + envKey + baseUrl). CLI-sourced keys are fully supported and tested (see "should preserve CLI-sourced apiKey" test case).

File: packages/core/src/models/modelsConfig.ts (hunk 3 above)
Comment (doudouOUC) [reply packages/core/src/models/modelsConfig.ts:916]: Considered but not adopting source-kind gating. Reasoning:

1. **`isUnchanged` already checks 4 dimensions**: authType + modelId + apiKeyEnvKey + baseUrl (added in d3563960c). When all four match, the provider is identical — preserving any source kind is safe.

2. **Provider-scoped env stale value scenario is extremely edge-case**: env vars are not normally rotated mid-session. And even if they are, `applyResolvedModelDefaults` always attempts a fresh `process.env[envKey]` read first — the restore only fires when the env var is absent, not when it's changed to a new value.

3. **Programmatic key preservation is correct behavior**: if a user called `updateCredentials` to set a key, and `syncAfterAuthRefresh` is called for the same unchanged model, dropping that key would be unexpected.

4. **Adding source-kind filtering would re-introduce the complexity** that wenshao's original review (the human one) correctly identified as fragile — "source.kind 猜是不可靠的". The current approach is simpler: same provider identity → preserve, different provider → discard.

File: packages/core/src/models/modelsConfig.ts [hunk 4]
```diff
@@ -877,7 +877,44 @@ export class ModelsConfig {
...
+        // applyResolvedModelDefaults clears it (i.e. process.env[envKey] is
+        // absent). For cross-provider switches (different modelId), we must
+        // NOT preserve the previous key — it may belong to a different
+        // service. Also detect hot-reload scenarios where the provider
+        // config changed in place (same modelId, different envKey/baseUrl)
+        // by comparing fields that applyResolvedModelDefaults sets. On the
+        // very first call (startup), apiKeyEnvKey is still undefined —
+        // treat that as "never applied" and skip the provider check.
+        // (See #3417)
+        const isProviderChanged =
```
Comment (wenshao) [inline packages/core/src/models/modelsConfig.ts:895]: **[Critical]** This treats every previous config without `apiKeyEnvKey` as if provider defaults were never applied. For a registry model that previously had no `envKey`, a hot-reload that adds an `envKey` or changes `baseUrl` will still leave `isUnchanged` true, so the old `apiKey` is restored after applying the new provider defaults. That can silently reuse a credential against a newly configured endpoint or provider env binding.

Please compare `baseUrl` independently, and treat `undefined -> someEnvKey` as a provider change once the previous config was already for the same registry model. It would also be worth adding regression coverage for no-`envKey` providers hot-reloading to add `envKey` and to change `baseUrl`.

_— gpt-5.5 via Qwen Code /review_

File: packages/core/src/models/modelsConfig.ts [hunk 5]
```diff
@@ -877,7 +877,44 @@ export class ModelsConfig {
...
+          this._generationConfig.apiKeyEnvKey !== undefined &&
+          (this._generationConfig.apiKeyEnvKey !== resolved.envKey ||
+            this._generationConfig.baseUrl !== resolved.baseUrl);
```
Comment (wenshao) [inline packages/core/src/models/modelsConfig.ts:898]: **[Critical]** Comparing the raw previous `baseUrl` to `resolved.baseUrl` can drop valid fallback keys for unchanged providers that omit `baseUrl`. `ModelRegistry` normalizes an omitted provider `baseUrl` to the default OpenAI URL, but startup resolution can leave `_generationConfig.baseUrl` undefined; with an `envKey` present, this makes `isProviderChanged` true and prevents restoring the settings/CLI/general-env `apiKey` on restart.

Please normalize the previous base URL to the same auth-type default before comparing, or only compare `baseUrl` when the previous config/source actually had a provider-applied `baseUrl`. A regression test with `envKey` set and `baseUrl` omitted would cover this case.

_— gpt-5.5 via Qwen Code /review_

**Review by wenshao — CHANGES_REQUESTED** [review]

File: packages/core/src/models/modelsConfig.ts (hunk 4 above)
Comment (doudouOUC) [reply packages/core/src/models/modelsConfig.ts:895]: Fixed in 0e3cb0a. Replaced the `apiKeyEnvKey !== undefined` guard with `baseUrl source === 'modelProviders'` as the "has been applied" signal. This works for both envKey and no-envKey models:

- After `applyResolvedModelDefaults`: baseUrl source is always `'modelProviders'` → `hasBeenApplied = true` → checks envKey and baseUrl changes
- At startup (before first apply): baseUrl source is `'settings'`/`'cli'` → `hasBeenApplied = false` → skips provider comparison → key preserved

Added test: "should NOT preserve apiKey when no-envKey model has baseUrl changed (hot-reload)".

File: packages/core/src/models/modelsConfig.ts (hunk 5 above)
Comment (doudouOUC) [reply packages/core/src/models/modelsConfig.ts:898]: Also fixed in 0e3cb0a. The guard now uses `baseUrl source === 'modelProviders'` instead of `apiKeyEnvKey !== undefined`. Since `applyResolvedModelDefaults` always sets baseUrl source to `'modelProviders'`, this is a reliable "has been applied" signal that does not depend on whether `envKey` or `baseUrl` were explicitly set in the provider config.

At startup (before first apply), baseUrl source is `'settings'`/`'cli'`/`'env'` → `hasBeenApplied = false` → baseUrl comparison is skipped entirely. This eliminates the false positive from `undefined !== defaultUrl`.

**Review by wenshao — APPROVED** [review]
No issues found. LGTM! ✅ _— gpt-5.5 via Qwen Code /review_
