### PR TITLE
fix: add explicit is_background param for shell tool

### LINKED ISSUE #346: During npm start development request qwen-cli hangs for minutes
### What happened?

Image

Environment:
Node.js version: 20.19.2
npm version: 10.8.2
Operating system: macOS 15.6

### What did you expect to happen?

The npm development server should start successfully and be ready for development without hanging indefinitely.

### Client information

<details>

```console
$ qwen /about
Version            0.0.7
Git Commit         14e6d3c0                             
Model              qwen3-coder-plus                     
Sandbox            no sandbox                           
OS                 darwin                               
Auth Method        qwen-oauth      
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by Mingholy**
## TLDR

_**Experimental optimization requests for review and evaluation.**_

Added explicit `is_background` parameter to the shell tool to provide better control over background vs foreground execution of shell commands. This improvement makes it clearer when commands should run in the background (like development servers) versus foreground (like build commands), enhancing user experience and tool reliability.

## Dive Deeper

Added an explicit `is_background` boolean parameter to the shell tool for better control over command execution modes.

**What Changed:**

- New `is_background` parameter (defaults to false)
- Background commands show `[background]` indicator in descriptions
- Updated documentation with clear usage examples
- Maintains backward compatibility with existing `&` syntax

**Why This Matters:**

- Makes intent explicit: background for long-running processes (servers, watchers), foreground for one-time commands (build, lint, test)
- Improves user experience with clearer execution control
- Reduces confusion about when commands will block vs run in background

## Reviewer Test Plan

Create a simple Hono HTTP server project to test the new `is_background` parameter:

1. **Setup Test Project:**

   ```bash
   mkdir test-hono-server && cd test-hono-server
   npm init -y
   npm install hono @types/node typescript eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin
   ```

2. **Create Basic Files:**
   - `src/server.ts`: Simple Hono server
   - `eslint.config.js`: ESLint configuration
   - `tsconfig.json`: TypeScript configuration
   - `package.json`: Add dev/build scripts

3. **Test Foreground Commands (should wait for completion):**

   ```bash
   # These should block and show results
   run_shell_command(command="npx eslint src/", is_background=false, description="Run ESLint")
   run_shell_command(command="npx tsc --noEmit", is_background=false, description="TypeScript check")
   run_shell_command(command="npm run build", is_background=false, description="Build project")
   ```

4. **Test Background Commands (should return immediately):**

   ```bash
   # This should start server in background and return immediately
   run_shell_command(command="npm run dev", is_background=true, description="Start Hono dev server")
   ```

5. **Verify Behavior:**
   - Foreground commands should show complete output and wait for finish
   - Background command should return immediately with `[background]` indicator
   - Dev server should be accessible on localhost while other commands can run
   - Background processes should appear in Background PIDs field

## Testing Matrix

|          | 🍏   | 🪟   | 🐧   |
| -------- | --- | --- | --- |
| npm run  | ✅   | ❓   | ❓   |
| npx      | ✅   | ❓   | ❓   |
| Docker   | ❓   | ❓   | ❓   |
| Podman   | ❓   | -   | -   |
| Seatbelt | ❓   | -   | -   |

## Linked issues / bugs

Fixes #346

### CODE REVIEW

File: packages/core/src/tools/shell.ts [hunk 1]
```diff
@@ -375,7 +413,7 @@ export class ShellTool extends BaseDeclarativeTool<
               '(OPTIONAL) Directory to run the command in, if not the project root directory. Must be relative to the project root directory and must already exist.',
           },
         },
-        required: ['command'],
+        required: ['command', 'is_background'],
```
Comment (tanzhenxin) [inline packages/core/src/tools/shell.ts:416]: I wonder if we should set `is_background` as optional parameter, since it has default value as false.

**Review by tanzhenxin — APPROVED** [review]

**Comment by Mingholy** [comment]
@tanzhenxin Setting `is_background` as an optional parameter may not work as expected. Did a little test:
`is_background` is not required:
image
During a cold start, if no additional instructions are given, the model tends to execute commands like `node server.js` or `npm run start` in the foreground, even though this is mentioned in the tool description.
While `is_background` is required:
image
I assume that when a model is forced to provide an `is_background` parameter, it is more likely to follow the instructions in the tool description to make the decision.

Based on the result above, I updated the docs to make a clear explanation and leave the discussion here.

**Comment by tanzhenxin** [comment]
> @tanzhenxin Setting `is_background` as an optional parameter may not work as expected. Did a little test: `is_background` is not required: image During a cold start, if no additional instructions are given, the model tends to execute commands like `node server.js` or `npm run start` in the foreground, even though this is mentioned in the tool description. While `is_background` is required: image I assume that when a model is forced to provide an `is_background` parameter, it is more likely to follow the instructions in the tool description to make the decision.
> 
> Based on the result above, I updated the docs to make a clear explanation and leave the discussion here.

LGTM!
