### PR TITLE
fix(core): recover from truncated tool calls via multi-turn continuation

### LINKED ISSUE #2: Where is the config saved?
The terminal ui doesn't appear to allow for me to edit my api configuration if something was wrong. Where is the configuration saved on the file system?

### PR DESCRIPTION
**Pull request by wenshao**
## Summary

Fixes #3049 — WriteFile/ReadFile tool calls fail with `params must have required property 'file_path'` when model output is truncated due to max_tokens limit.

## Root cause

When the model generates a large tool call (e.g., WriteFile with a big HTML file), the response can exceed the output token limit. The adaptive escalation (#2898) retries at 64K, but:

1. For models with output limits > 64K (Opus 128K, GPT-5 128K), the fixed 64K cap wastes available capacity
2. If the response is still too large even after escalation, the tool call parameters are incomplete (e.g., `file_path` missing) and the user sees a confusing validation error

## Recovery flow / 恢复流程

```
Request (max_tokens = 8K)
│
▼
┌─────────────────────────┐
│  Response truncated?     │──── No ──▶ Done ✓
│  (MAX_TOKENS)            │
└───────────┬──────────────┘
            │ Yes
            ▼
┌──────────────────────────────────────────────────┐
│  Layer 1: Escalate to model output limit         │
│  第一层：提升到模型实际输出上限                      │
│  ┌────────────────────────────────────────────┐  │
│  │ Pop partial response from history          │  │
│  │ RETRY (isContinuation: false → reset UI)   │  │
│  │ Re-send at max(64K, model output limit)    │  │
│  └────────────────────────────────────────────┘  │
└───────────┬──────────────────────────────────────┘
            │
            ▼
┌─────────────────────────┐
│  Still truncated?        │──── No ──▶ Done ✓
│  (MAX_TOKENS)            │
└───────────┬──────────────┘
            │ Yes
            ▼
┌──────────────────────────────────────────────────┐
│  Layer 2: Multi-turn recovery (up to 3×)         │
│  第二层：多轮续写恢复（最多 3 次）                    │
│  ┌────────────────────────────────────────────┐  │
│  │ If truncated turn has a functionCall →     │  │
│  │   skip (would break API contract)          │  │
│  │ Else:                                      │  │
│  │   Keep partial response in history         │  │
│  │   Push user message: "Resume directly..."  │  │
│  │   RETRY (isContinuation: true → keep buf)  │  │
│  │   Re-send with updated history             │  │
│  │   Model continues from where it left off   │  │
│  └──────────────┬─────────────────────────────┘  │
│                 │                                 │
│          ┌──────┴──────┐                          │
│          │ Succeeded?  │── Yes ──▶ Done ✓         │
│          └──────┬──────┘                          │
│                 │ No (still truncated)            │
│                 ▼                                 │
│          attempt < 3? ── Yes ──▶ loop back ↑      │
└───────────┬──────────────────────────────────────┘
            │ No (exhausted or functionCall skip)
            ▼
┌──────────────────────────────────────────────────┐
│  Layer 3: Tool scheduler fallback                │
│  第三层：工具调度器兜底                               │
│  ┌────────────────────────────────────────────┐  │
│  │ Reject truncated Edit/Write tool calls     │  │
│  │ Return guidance: "You MUST split into      │  │
│  │ smaller parts — write skeleton first,      │  │
│  │ then edit incrementally."                  │  │
│  └────────────────────────────────────────────┘  │
└──────────────────────────────────────────────────┘
```

### 1. Escalate to the model's actual output limit / 提升到模型实际输出上限

Instead of a fixed 64K escalation target, use `Math.max(ESCALATED_MAX_TOKENS, tokenLimit(model, 'output'))`.

不再固定提升到 64K，而是取 64K 与模型实际输出上限的较大值：

| Model | Before | After |
|---|---|---|
| Claude Opus 4.6 | 64,000 | **131,072** |
| GPT-5 / o-series | 64,000 | **131,072** |
| Qwen3.x | 64,000 | 65,536 |
| Unknown models | 64,000 | 64,000 (floor) |

### 2. Multi-turn recovery after escalation / 提升后多轮续写恢复

When the escalated response is still truncated (finishReason === MAX_TOKENS):

- **If the truncated turn contains a `functionCall`**, recovery is skipped to avoid producing an invalid `model(functionCall) → user(text)` API sequence. The tool scheduler's layer-3 fallback handles it.
- **Otherwise**:
  1. Keep the partial model response in history
  2. Inject a recovery user message: *"Output token limit hit. Resume directly — no recap. Pick up mid-thought. Break remaining work into smaller pieces."*
  3. Re-send the request so the model continues from where it left off
  4. Repeat up to 3 times

当提升后响应仍然被截断时：若截断轮含 `functionCall` 则跳过恢复（交给 layer 3，避免破坏 API 序列合约）；否则保留部分响应并注入恢复消息，让模型从断点续写，最多 3 次。

The recovery RETRY uses `isContinuation: true` so the UI preserves the text buffer (appending continuation text) rather than resetting it (as done for escalation).

恢复 RETRY 使用 `isContinuation: true`，UI 保留文本缓冲区（追加续写内容），而非像提升重试那样重置。

If a recovery attempt fails (e.g., empty response, network error), the catch block pops the dangling recovery message, emits a synthetic `STOP` chunk for a clean UI terminal signal, and exits the loop gracefully.

如果恢复尝试失败（空响应、网络错误等），catch 会弹出悬空的恢复消息，发出合成的 `STOP` chunk 作为 UI 终止信号，然后优雅退出循环。

### 3. Stronger truncation guidance (fallback) / 加强截断引导（兜底）

If recovery is exhausted or skipped, the tool scheduler's truncation rejection uses more directive language:

恢复耗尽或跳过后，工具调度器的截断拒绝消息改用更明确的指令：
- "you MUST split" instead of "consider splitting" / "必须拆分"替代"建议拆分"
- "Do NOT retry with the same large content" / "不要用同样的大内容重试"
- Concrete instructions: "first write_file with skeleton, then edit incrementally" / 具体步骤：先写骨架，再用 edit 逐步补充

### Bug fixes / 附带修复

- **Duplicate tool execution on RETRY / RETRY 时工具重复执行**: `toolCallRequests` in `useGeminiStream.ts` was never cleared on Retry events, causing tool calls from a truncated attempt to persist alongside the retried attempt's calls. Now cleared on every RETRY. / `toolCallRequests` 在 Retry 事件时从未清空，导致截断尝试的工具调用与重试的调用并存。现已在每次 RETRY 时清空。
- **Text duplication on escalation / 提升时文本重复**: `geminiMessageBuffer` / `thoughtBuffer` were not reset on escalation RETRY, causing the 8K partial text to be concatenated with the full escalated response. Now reset when `isContinuation` is false. / 提升 RETRY 时 buffers 未重置，导致 8K 部分文本与完整提升响应拼接。现在当 `isContinuation` 为 false 时重置。
- **Partial text lost during continuation / 续写时部分文本丢失**: On a continuation RETRY, clearing `pendingHistoryItem` caused `handleContentEvent` to see a null pending item, create a fresh one, and reset the buffer to just the new chunk. Now the pending item is kept on continuation so the continuation text appends correctly. / 续写 RETRY 时清空 `pendingHistoryItem` 导致 `handleContentEvent` 看到 null 后创建新 item 并把 buffer 重置为仅新 chunk。现在续写时保留 pending item，续写文本正确追加。

## Test plan / 测试计划

- [x] 199 core tests pass (coreToolScheduler, geminiChat, turn, client) — 5 new recovery-loop tests / 199 个核心测试通过，含 5 个新恢复循环测试
- [x] 74 useGeminiStream UI tests pass / 74 个 UI 测试通过
- [x] TypeScript build passes for core and cli packages / TypeScript 构建通过
- [x] **Manual end-to-end verification via tmux** with debug logging enabled, using glm-5.1 (16K output limit) and a prompt asking for an 800-line HTML landing page / **tmux 端到端手工验证**，用 glm-5.1（16K 输出上限）+ 800 行 HTML 生成请求

### E2E trace observed / E2E 追踪结果

```
[INFO] Output truncated at capped default. Escalating to 64000 tokens.       ← Layer 1 ✓
[INFO] Skipping recovery: truncated turn contains functionCall; deferring
       to tool scheduler fallback.                                           ← Layer 2 guard ✓
```

UI sequence:
1. Initial 8K → MAX_TOKENS (⚠️ Response truncated shown)
2. Escalated to model's 16K cap → MAX_TOKENS again (⚠️ shown again), escalated response contained a partial `write_file` functionCall
3. Recovery guard fires on iteration 1 because the truncated turn has a `functionCall` → skips recovery
4. Tool scheduler applies the new truncation guidance
5. Model reads guidance, responds: *"内容太大，我需要分段写入。先创建骨架，再逐步追加。"* (Content is too large, I need to write it in parts. Create the skeleton first, then progressively append.)
6. Model calls `write_file` with a **21-line skeleton** containing `PLACEHOLDER - CSS will be injected` / `PLACEHOLDER - JS will be injected` markers — **exactly the behavior the new guidance is designed to produce**

This confirms all three defense layers work end-to-end with a real model, and that tanzhenxin's review fix #2 (functionCall guard) correctly prevents the invalid API sequence in practice.

此测试证实三层防御在真实模型调用下端到端工作，且 tanzhenxin 指出的 Issue 2 修复（functionCall guard）在实际场景下正确防止了无效的 API 序列。

### CODE REVIEW

**Review by wenshao — COMMENTED** [review]
**[Suggestion]** The ACP cron path starts a background rewrite with `this.messageRewriter.flushTurn(ac.signal)`, but unlike the normal prompt path it never waits for pending rewrites before returning. That can drop the final rewritten ACP progress update if the cron turn finishes immediately after scheduling the rewrite. Consider mirroring the normal prompt flow by awaiting `this.messageRewriter.waitForPendingRewrites()` before `#executeCronPrompt()` returns.

_— gpt-5.4 via Qwen Code /review_

**Review by tanzhenxin — CHANGES_REQUESTED** [review]
## Review

Adds a well-structured 3-layer recovery for truncated model output. The recovery loop is cleanly bounded by `MAX_OUTPUT_RECOVERY_ATTEMPTS`, and the two bug fixes (duplicate tool execution on RETRY, text duplication on escalation) are real and correct. However, the continuation path has two correctness bugs.

### Issues

1. **Partial text lost from display during continuation.** On a continuation RETRY, `setPendingHistoryItem(null)` clears the partial text. When `handleContentEvent` runs for the first continuation chunk, it sees a null pending item, creates a new one, and resets `geminiMessageBuffer = eventValue` — discarding the preserved buffer. The user loses the beginning of the recovered response. Suggestion: commit the partial text to the static item list via `addItem` before clearing, or don't clear `pendingHistoryItemRef.current` and let the continuation append to it.

2. **Recovery on truncated tool-call turns corrupts conversation state.** If the truncated turn already emitted a complete `functionCall`, the recovery injects a plain user message — creating `model(functionCall) → user(text)` with no `functionResponse`. This is an invalid sequence for the API. Suggestion: skip multi-turn recovery when the truncated turn contains `functionCall` parts, and let the existing tool scheduler fallback (layer 3) handle those cases.

3. **Recovery errors swallowed after partial chunks emitted.** A recovery attempt can yield chunks then fail. The catch block breaks without emitting an error event, leaving the UI with partial text and no failure indication. Suggestion: emit an error or warning event in the catch block.

### Verdict

REQUEST_CHANGES — The text loss and conversation state corruption need to be fixed. Test coverage for the new recovery loop is also expected.

**Comment by wenshao** [comment]
Thanks for the thorough review!

**Re High #1 (backoff between recovery attempts):** `makeApiCallAndProcessStream` internally uses `retryWithBackoff` which already handles HTTP 429 retries with exponential backoff. Each recovery request has different history content (partial response + recovery message), so deduplication/caching is not a concern. Adding an extra delay would increase latency for every recovery attempt without meaningful benefit.

**Re High #2 (guard before pushing recovery message):** This is already handled by the catch block. If a recovery attempt fails, the catch pops the dangling user message and breaks out of the loop. In the success path, `processStreamResponse` always pushes a model response to history before control returns to the recovery loop, so the history maintains proper alternating user/model structure before the next recovery message is pushed.

**Re Medium #3-5:** Acknowledged as style preferences. `tokenLimit` is called once per escalation (no caching needed), `escalatedFinishReason` type annotation already implies `undefined` initial value, and `toolCallRequests` is a locally-scoped `const` array that is always defined.

**Re Low #6-9:** Good suggestions for future iterations. Keeping them out of this PR scope to minimize change surface.

**Comment by tanzhenxin** [comment]
Hi @wenshao, looks like your earlier response was addressing the github-actions bot review. Could you take a look at the three critical issues I flagged in my review above?

1. **Partial text lost from display during continuation** — when `setPendingHistoryItem(null)` clears the pending item before the continuation chunk arrives, `handleContentEvent` creates a fresh pending item and resets `geminiMessageBuffer = eventValue`, so the user loses the beginning of the recovered response. This is a visible regression for the exact scenario the PR targets.

2. **Recovery on truncated tool-call turns produces invalid history** — if the truncated turn contains `functionCall` parts, appending a plain user recovery message yields a `model(functionCall) → user(text)` sequence with no intervening `functionResponse`, which the API documents as invalid. The already-emitted tool call is also lost. Gating the recovery path on "no functionCall parts in the truncated turn" would be the cleanest fix.

3. **Recovery errors swallowed after partial chunks emitted** — if a recovery attempt yields chunks then fails, the catch block pops the prompt and breaks without emitting an error event, leaving the UI with partial text and no terminal signal.

Happy to discuss if you disagree on any of these — (2) in particular would be good to confirm against real API behavior.

**Comment by wenshao** [comment]
@tanzhenxin You are absolutely right on all three — apologies for conflating your review with the bot review earlier.

Addressed in f683830ad:

**1. Partial text lost during continuation** — Kept both `pendingHistoryItemRef.current` and the buffers on continuation RETRY. `handleContentEvent` now sees an existing gemini pending item and appends instead of resetting the buffer.

**2. Recovery on truncated tool-call turns** — Added a guard at the top of the recovery loop: if the last model entry in history contains any `functionCall` part, `break` out and defer to the layer-3 tool scheduler fallback. This avoids the invalid `model(functionCall) → user(text)` sequence and preserves the tool-call path you pointed out was being silently dropped.

**3. Recovery errors swallowed after partial chunks** — In the catch block, now emit a synthetic chunk with `finishReason: STOP` before breaking, so turn.ts yields a `Finished` event and the UI gets a proper terminal signal. The partial chunks from prior successful iterations remain in the transcript as the user-visible response; the failure is logged via `debugLogger.warn`.

Regarding (2), I verified by tracing the history structure after the guard fires: the truncated model turn with functionCall stays intact, `wasOutputTruncated=true` is already set on `pendingToolCalls` by turn.ts, and `coreToolScheduler` then applies `TRUNCATION_EDIT_REJECTION` / `TRUNCATION_PARAM_GUIDANCE` as the fallback. No invalid sequence is written to history.

Will add targeted tests for the recovery loop next.

**Comment by wenshao** [comment]
Added 4 targeted recovery-loop tests in b9340c154 covering:

- **Recovery fires when escalation is still truncated** — verifies two RETRY events (escalation with `isContinuation` undefined, continuation with `isContinuation: true`) and three API calls.
- **Recovery skipped when truncated turn has functionCall** — verifies no continuation RETRY, only 2 API calls, and history ends with the functionCall part intact (layer-3 fallback takes over).
- **Recovery capped at 3 attempts** — persistent MAX_TOKENS triggers exactly `1 + 1 + 3 = 5` API calls.
- **Recovery catch emits synthetic STOP chunk and pops dangling user message** — when a recovery attempt yields no chunks (→ `InvalidStreamError`), the last emitted chunk has `finishReason: STOP` and history ends on a model turn.

Total: 198 tests pass (194 existing + 4 new).

**Comment by wenshao** [comment]
Noting the earlier `/review` suggestion about the ACP cron path (`messageRewriter.flushTurn` / `waitForPendingRewrites` / `#executeCronPrompt`) — that code lives in `packages/cli/src/acp-integration/session/Session.ts` which this PR does not modify. The suggestion appears to be out of scope and was triggered against unrelated code. Flagging here so reviewers do not chase it.

Only changed files in this PR:
- `packages/core/src/core/geminiChat.ts`
- `packages/core/src/core/turn.ts`
- `packages/core/src/core/coreToolScheduler.ts`
- `packages/cli/src/ui/hooks/useGeminiStream.ts`
- `packages/core/src/core/geminiChat.test.ts`
- `docs/design/adaptive-output-token-escalation/...`

File: packages/core/src/core/geminiChat.ts [hunk 1]
```diff
@@ -525,18 +557,109 @@ export class GeminiChat {
...
+              }
+            } catch (recoveryError) {
+              // If a recovery attempt fails (e.g., empty response, network
+              // error), stop recovering and let the partial output stand.
+              // Pop the dangling recovery message to keep history valid.
+              if (
+                self.history.length > 0 &&
+                self.history[self.history.length - 1].role === 'user'
+              ) {
+                self.history.pop();
```
Comment (wenshao) [inline packages/core/src/core/geminiChat.ts:644]: **[Critical]** Recovery `catch` block only pops the dangling user message, but `processStreamResponse` unconditionally pushes a model entry to `this.history` (line 1083) *before* its validation check throws. When a recovery stream fails validation (e.g., empty stream → `NO_FINISH_REASON`), the model entry is left in history.

This creates consecutive model entries. When `extractCuratedHistory` runs on the next turn, the empty model entry fails `isValidContent`, causing the **entire group** (including valid partial output already shown to the user) to be discarded. The resulting curated history may have two consecutive user entries, which most API providers reject.

```suggestion
            } catch (recoveryError) {
              // If a recovery attempt fails (e.g., empty response, network
              // error), stop recovering and let the partial output stand.
              // Pop the model entry that processStreamResponse pushed
              // before throwing (it may be empty or contain partial content).
              if (
                self.history.length > 0 &&
                self.history[self.history.length - 1].role === 'model'
              ) {
                self.history.pop();
              }
              // Pop the dangling recovery user message to keep history valid.
              if (
                self.history.length > 0 &&
                self.history[self.history.length - 1].role === 'user'
              ) {
                self.history.pop();
              }
```

_— glm-5.1 via Qwen Code /review_

File: packages/core/src/core/geminiChat.test.ts [hunk 2]
```diff
@@ -2290,4 +2290,252 @@ describe('GeminiChat', async () => {
...
+        (lastChunk as { value: GenerateContentResponse }).value.candidates?.[0]
+          ?.finishReason,
+      ).toBe('STOP');
+
+      // History should NOT end with a dangling user recovery message.
+      const history = chat.getHistory();
+      const lastEntry = history[history.length - 1]!;
+      // Last entry should be the escalated model response, not a user
+      // recovery message.
+      expect(lastEntry.role).toBe('model');
```
Comment (wenshao) [inline packages/core/src/core/geminiChat.test.ts:2493]: **[Suggestion]** This test only checks `lastEntry.role === 'model'` but doesn't verify there are no consecutive model entries. The Critical bug above passes this test because the last entry IS `'model'` (the empty one from `processStreamResponse`), masking the history corruption.

Consider adding stricter history integrity checks:

```suggestion
      // Verify no consecutive model entries (history must alternate).
      for (let i = 1; i < history.length; i++) {
        expect(history[i]!.role).not.toBe(history[i - 1]!.role);
      }
      const lastEntry = history[history.length - 1]!;
      // Last entry should be the escalated model response, not a user
      // recovery message.
      expect(lastEntry.role).toBe('model');
      // The last model entry should have actual content (not empty parts
      // from a failed processStreamResponse push).
      expect(lastEntry.parts.length).toBeGreaterThan(0);
```

_— glm-5.1 via Qwen Code /review_

File: packages/core/src/core/geminiChat.ts (hunk 1 above)
Comment (wenshao) [reply packages/core/src/core/geminiChat.ts:644]: After re-reading `processStreamResponse` (lines 1066–1086), this is a false positive from the automated `/review` pass.

The validation check at line 1066 (`if (!hasToolCall && (!hasFinishReason || !hasAnyContent))`) runs **before** `this.history.push` at line 1080. When the recovery stream is empty, `NO_FINISH_REASON` is thrown during validation and execution never reaches the push. The existing catch block's "pop the dangling user recovery message" is sufficient — there is no stale model entry to clean up.

I verified this end-to-end: the `should pop dangling recovery message and emit STOP chunk when recovery throws` test, with the strengthened alternating-role assertion added in 789ebd79e, passes on the current code — if a phantom empty-parts model entry were being left behind the assertion would fail. Closing this thread, no source change required.

File: packages/core/src/core/geminiChat.test.ts (hunk 2 above)
Comment (wenshao) [reply packages/core/src/core/geminiChat.test.ts:2493]: Applied in 789ebd79e:

- Added the alternating-role check (`expect(history[i].role).not.toBe(history[i - 1].role)` for every adjacent pair).
- Added `expect(lastEntry.parts.length).toBeGreaterThan(0)` to guard against any future regression that pushes an empty-parts model placeholder.

Test passes. The stricter assertions also happen to refute the Critical in the sibling thread — if any path in `processStreamResponse` were leaving a dangling empty-parts model entry on recovery failure, the new `parts.length > 0` assertion would fail.

File: packages/core/src/core/geminiChat.ts [hunk 3]
```diff
@@ -525,18 +557,109 @@ export class GeminiChat {
...
+            debugLogger.info(
+              `Output still truncated after escalation. ` +
+                `Recovery attempt ${recoveryCount}/${MAX_OUTPUT_RECOVERY_ATTEMPTS}.`,
+            );
+            // The partial model response is already in history
+            // (pushed by processStreamResponse). Push a recovery user
+            // message so the model sees its partial output and continues.
+            self.history.push(
+              createUserContent([{ text: OUTPUT_RECOVERY_MESSAGE }]),
+            );
```
Comment (wenshao) [inline packages/core/src/core/geminiChat.ts:612]: **[Suggestion]** This recovery prompt is being persisted as a real user turn in `history`, so every later model call will continue to see an internal control instruction ("resume directly / break remaining work into smaller pieces") that the user never actually sent. That can bias subsequent turns and also pollute history-based features like compression, replay, export, or debugging.

Consider treating the recovery prompt as ephemeral control state instead of durable conversation history, or removing it once the continuation response has been appended successfully.

_— gpt-5.4 via Qwen Code /review_

Comment (wenshao) [reply packages/core/src/core/geminiChat.ts:612]: Valid concern — the `OUTPUT_RECOVERY_MESSAGE` was a synthetic control prompt that persisted as a real user turn, so every later API call, compression pass, and replay/export saw it.

Fixed in 9f7327368 by post-loop coalescing: after the recovery `while` exits, each successfully-completed `(user_recovery, model_continuation)` pair is merged back into the preceding model turn via a new `coalesceRecoveryPairs` helper (drops the user entry, concatenates continuation parts onto the preceding model's parts). Failed iterations already pop their user turn in the catch block, so they need no cleanup.

Added a focused test `should coalesce successful recovery iterations into the preceding model turn` that runs escalation + two successful recovery iterations + a clean STOP, then asserts:

1. `history.length === 2` (one user turn, one model turn)
2. The control prompt text (`"Resume directly"`, `"Output token limit hit"`) appears **nowhere** in `JSON.stringify(history)`
3. Merged text is `"BCD"` (escalation + recovery 1 + recovery 2, in order)

All 52 existing `geminiChat` tests still pass.

**Review by wenshao — COMMENTED** [review]
No issues found. LGTM! ✅ _— gpt-5.4 via Qwen Code /review_

**Review by tanzhenxin — APPROVED** [review]
All three blockers from the prior review are addressed with targeted tests (partial-text preservation, functionCall guard with cross-iter coverage, synthetic STOP on catch). The post-loop `coalesceRecoveryPairs` cleanup for the control prompt is a nice catch — keeps durable history free of synthetic turns. LGTM.
