### PR TITLE
fix(mcp): update OAuth client name for Figma MCP server compatibility

### LINKED ISSUE #1095: `http` protocol mcp server failing
### What happened?

I am using `Figma` MCP server and this is the `settings.json` I have.
```json
  "mcpServers": {
    "Figma": {
      "httpUrl": "https://mcp.figma.com/mcp"
    },}
```

When running `qwen` it prompts me with `Command command not found` during MCP server initialization.

This could be an issue of how it is different for setting these servers in `qwen` to `gemini` because it is identical and it works in `gemini`.

Image

### What did you expect to happen?

Connect with the MCP server

### Client information

<details>
<summary>Client Information</summary>

Run `qwen` to enter the interactive CLI, then run the `/about` command.

```console
╭───────────────────────────────────────────────────────────────────────────────────╮
│                                                                                   │
│ About Qwen Code                                                                   │
│                                                                                   │
│ CLI Version                 0.2.3                                                 │
│ Git Commit                  442a9aed                                              │
│ Model                       coder-model                                           │
│ Sandbox                     no sandbox                                            │
│ OS Platform                 linux                                                 │
│ OS Arch                     x64                                                   │
│ OS Release                  6.17.4-arch2-1                                        │
│ Node.js Version             v22.20.0                                              │
│ NPM Version                 10.9.3                                                │
│ Session ID                  b4330577-9f68-42e6-90e7-3a4171b0799d                  │
│ Auth Method                 qwen-oauth                                            │
│ Memory Usage                228.8 MB                                              │
│                                                                                   │
╰───────────────────────────────────────────────────────────────────────────────────╯

```

</details>

### Login information

Oauth

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by afarber**
## TLDR

Update the OAuth dynamic client registration `client_name` from `"Gemini CLI (Google ADC)"` to `"Gemini CLI MCP Client"` to fix Figma MCP server authentication failures.

## Dive Deeper

Figma recently changed their MCP server's OAuth client whitelist. The old client name `"Gemini CLI (Google ADC)"` is no longer accepted, causing HTTP 401 Unauthorized errors during OAuth dynamic client registration.

This fix updates the client name in two files:

 Changes:

 - Created `packages/core/src/mcp/constants.ts` for OAuth constants
 - Updated `oauth-provider.ts`, `google-auth-provider.ts`, and `sa-impersonation-provider.ts` to use the constants
 - The new client name `"Gemini CLI MCP Client"` matches what Figma now expects
  
## Reviewer Test Plan

1. Add Figma MCP server to `~/.qwen/settings.json`:
     ```json
     {
       "mcpServers": {
         "Figma": {
           "httpUrl": "https://mcp.figma.com/mcp",
           "oauth": {
             "enabled": true
           }
         }
       }
     }
    ```
2. Run `npm run build && npm run start`
3. On first startup, warnings in Debug Console (ctrl+o) are expected:
  ```
  ✖ MCP server 'Figma' requires OAuth authentication. Please authenticate using the /mcp auth command.
  ```
4. Issue the prompt `/mcp auth Figma`
5. Verify browser opens for Figma OAuth authentication
6. Complete login and verify "Successfully authenticated" message appears
7. Issue the prompt `/mcp` to verify Figma tools are available
8. Restart Qwen Code - the warnings should no longer appear since the token is now cached in ~/.qwen/mcp-oauth-tokens.json

Without this fix: /mcp auth Figma fails with Client registration failed: 403 Forbidden

Note: A Figma account is required to test this fix.

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | yes | ❓  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Fixes #1095

### CODE REVIEW

File: packages/core/src/mcp/constants.ts [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+ * @license
+ * Copyright 2025 Qwen
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+/**
+ * OAuth client name used for MCP dynamic client registration.
+ * This name must match the allowlist on MCP servers like Figma.
+ */
+export const MCP_OAUTH_CLIENT_NAME = 'Gemini CLI MCP Client';
```
Comment (pomelo-nwu) [inline packages/core/src/mcp/constants.ts]: Good design. Once more MCP authentications support Qwen Code, we will update this MCP_OAUTH_CLIENT_NAME.
