### PR TITLE
fix(windows): resolve silent failures caused by CRLF line endings (#1868)

### LINKED ISSUE #1868: Bug: Sub-agents created outside qwen-code /agent create are not detected on Windows
### What happened?

On Windows, sub-agent markdown files created or edited with external editors (e.g., Notepad) does not appear in the agent list and is silently ignored by qwen-code. 

Steps to reproduce:
```console
1. On Windows, create/edit a sub-agent markdown file using Notepad / VS Code (same format as a working agent).
2. Save it in the local agents directory.
3. Start or reload qwen-code.
4. Run the command that lists agents.
```

Result: the sub-agent is not detected.

### What did you expect to happen?

Sub-agents created or edited outside qwen-code (for example, with Notepad or other editors) should be detected and usable by qwen-code just like agents created with /agent create.

### Client information

<details>
<summary>Client Information</summary>

Run `qwen` to enter the interactive CLI, then run the `/about` command.

```console
Status   
                                                      
Qwen Code      0.10.4 (509a88a4)                      
Runtime        Node.js v20.20.0 / npm 11.10.0          
OS             win32 x64 (10.0.26100)                 
                                                      
Auth           qwen-oauth                             
Model          coder-model                            
Session ID     1e483c60-b9c2-4348-aaf5-935f23e6306d   
Sandbox        no sandbox                             
Proxy          no proxy                               
Memory Usage   165.0 MB                               

```

</details>

### Login information

I log in via the qwen-oauth. No API key or special config is used.

### Anything else we need to know?

I’d like to work on this issue.

### PR DESCRIPTION
**Pull request by Aayushyaash**
## TLDR

Fixes a critical bug on Windows where subagents, skills, and Claude-converted plugins were silently ignored due to CRLF (`\r\n`) line endings. Standardizes text normalization across all core managers.

**Crucially, this fix also resolves issues where agents downloaded from the Claude marketplace (e.g., via `qwen extensions install`) were not being detected after installation inside Windows.**

## Dive Deeper

The root cause was that several key parsers used strict regex patterns expecting only `\n` newlines, causing files saved with CRLF (common in Windows editors like Notepad or VS Code or any other external editor with CRLF enabled) to fail to load silently.

### Solution: Unified Normalization Layer
Moved from a fragmented approach with duplicate logic and unprotected entry points to a unified, "Normalize-First" architecture. Inspired from original **Skill Manager & Skill Load** pre-normalization solution.

#### Logic Flow: Before vs After
```text
┌─────────────────────────────────────────────────────────────────────────────┐
│                         BEFORE THE FIX (Original Code)                      │
├─────────────────────────────────────────────────────────────────────────────┤
│                                                                             │
│  1. subagent-manager.ts (BROKEN - NO NORMALIZATION)                         │
│     read file → content.match(frontmatterRegex) → parseYaml                 │
│                                    ↓                                        │
│                            ❌ FAILS ON WINDOWS                              │
│                                                                             │
│  2. skill-manager.ts / skill-load.ts (DUPLICATE CODE)                       │
│     read file → normalizeSkillFileContent() → regex → parseYaml             │
│              └─────────── duplicated logic ──────────────┘                  │
│                                                                             │
│  3. claude-converter.ts (BROKEN - NO NORMALIZATION)                         │
│     read file → content.match(frontmatterRegex) → parseYaml                 │
│                                    ↓                                        │
│                            ❌ FAILS ON WINDOWS                              │
│                                                                             │
└─────────────────────────────────────────────────────────────────────────────┘
┌─────────────────────────────────────────────────────────────────────────────┐
│                          AFTER THE FIX (Current Code)                       │
├─────────────────────────────────────────────────────────────────────────────┤
│                                                                             │
│  NEW: textUtils.ts - Centralized normalizeContent()                         │
│       └── strips UTF-8 BOM, converts \r\n → \n, converts \r → \n            │
│                                                                             │
│  1. subagent-manager.ts                                                     │
│     read file → normalizeContent() → regex → parseYaml ✅                   │
│                                                                             │
│  2. skill-manager.ts / skill-load.ts                                        │
│     read file → normalizeContent() → regex → parseYaml ✅                   │
│              └──────── removed duplicates ─────────┘                        │
│                                                                             │
│  3. claude-converter.ts                                                     │
│     read file → normalizeContent() → regex → parseYaml ✅                   │
│                                                                             │
└─────────────────────────────────────────────────────────────────────────────┘
```

### Changes Made:
- **Global Utility**: Added `normalizeContent` in `packages/core/src/utils/textUtils.ts` (strips BOM, converts CRLF/CR to LF).
- **Subagent Manager**: Integrated normalization in `parseSubagentContent` (`subagent-manager.ts`).
- **Skill Manager & Skill Load**: Replaced redundant local logic with the global utility for better maintainability.
- **Claude Converter**: Fixed agent file extraction and standardized test folder naming (`src-agents`) to avoid resource collection conflicts.
- **Tests**: Added CRLF integration tests in `subagent-manager.test.ts`, `textUtils.test.ts`, and `claude-converter.test.ts`.

## Reviewer Test Plan

1. **Verify Subagent Loading**: Create a subagent on Windows using an external editor (Notepad), save it, and ensure it is detected by `qwen-code`.
2. **Verify Skill Loading**: Verify that skills authored with CRLF continue to load correctly.
3. **Verify Claude Conversion**: Run the new test case `should successfully convert agent files with Windows CRLF endings`.
4. **Automated Tests**: Run `npm run test` to ensure no regressions in the 3680+ existing tests.

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | -   | ✅  | -   |
| npx      | -   | ✅  | -   |

Tested on Windows 11.

## Visual Proof

**Before Fix: Marketplace agents missing on Windows**

image

**After Fix: Marketplace agents successfully detected**

image

## Linked issues / bugs

Fixes #1868

### CODE REVIEW

File: packages/core/src/extension/claude-converter.ts [hunk 1]
```diff
@@ -226,10 +227,11 @@ async function convertAgentFiles(agentsDir: string): Promise<void> {
 
     try {
       const content = await fs.promises.readFile(filePath, 'utf-8');
+      const normalizedContent = normalizeContent(content);
 
       // Parse frontmatter
       const frontmatterRegex = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/;
```
Comment (LaZzyMan) [inline packages/core/src/extension/claude-converter.ts]: The skill-manager.ts version uses (?:\n|$) to allow frontmatter to end with or without a trailing newline, which is more robust. Consider applying the same pattern to claude-converter.ts for consistency.
```typescript
const frontmatterRegex = /^---\n([\s\S]*?)\n---(?:\n|$)([\s\S]*)$/;
```

**Review by DennisYu07 — APPROVED** [review]
