### PR TITLE
fix: Strengthen error handling in qwenOAuth2.ts to prevent unhandled 'error' event

### LINKED ISSUE #1674: qwen-code encountered an error during initialization on OrangePi RV2
### What happened?

OrangePi RV2 is a RISC-V development version that throws an error during initialization, while Claude does not.

### What did you expect to happen?

No errors during initialization

### Client information

Qwen Code: 0.8.2 (bb53d92d)
Runtime: Node.js v22.22.0 / npm 10.9.4
OS: linux riscv64 (6.6.63-ky)
Auth: openai (https://dashscope.aliyuncs.com/compatible-mode/v1)
Model: qwen3-coder-plus
Session ID: 71c2fede-c39f-403e-a6a0-77ae765aa41e
Sandbox: no sandbox
Proxy: no proxy
Memory Usage: 223.9 MB

```error info
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -2,

```

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by Ojhaharsh**
Hi @wenshao,

As suggested in your review of #1675, this PR addresses the root cause of the crash reported in issue #1674

### The Issue
The crash (`Unhandled 'error' event`) occurs in `packages/core/src/qwen/qwenOAuth2.ts` when the `open` package fails to spawn a browser process (common on RISC-V/OrangePi headless environments).

### The Fix
I updated the `launchBrowser` helper function to:
1.  Explicitly check if `childProcess` is valid before attaching listeners.
2.  Attach the `childProcess.on('error')` listener immediately after `await open()` to minimize race conditions.
3.  Ensure errors are caught via `try/catch` AND the event listener, logging gracefully via `debugLogger` instead of crashing.

This implements your suggestion to "attach the error listener before the child has a chance to emit."

### Relation to PR #1675
This is the second part of the split you requested:
- **PR #1675:** Handles utility docs/tests/lint (microsoft-edge fallback).
- **This PR:** Fixes the actual crash source in `qwenOAuth2.ts`.

--
(Fixes #1674)
Ready for review!

### CODE REVIEW

File: packages/core/src/qwen/qwenOAuth2.ts [hunk 1]
```diff
@@ -8,7 +8,7 @@ import crypto from 'crypto';
 import path from 'node:path';
 import { promises as fs } from 'node:fs';
 import * as os from 'os';
```
Comment (wenshao) [inline packages/core/src/qwen/qwenOAuth2.ts:10]: **[Suggestion]** `ChildProcess` is only used as a type here, so this should be a type-only import to satisfy the repo's lint rule.

```suggestion
import type { ChildProcess } from 'node:child_process';
```

_— gpt-5.4 via Qwen Code /review_

**Comment by Ojhaharsh** [comment]
Hi @wenshao,

This PR contains the robust error handling fix for `qwenOAuth2.ts` to prevent the **Unhandled 'error' event** crash on RISC-V/OrangePi environments (Issue #1674).

**Status:**

✅ **Lint Fixed**: Updated `ChildProcess` to a type-only import as suggested.  
✅ **All Checks Green**: Lint, Tests (Mac/Ubuntu/Windows), and CodeQL are passing.  
✅ **Logic Verified**: The `launchBrowser` function now safely attaches error listeners and handles failures gracefully via `debugLogger`.

This addresses the root cause of the crash you identified. It is designed to be merged alongside PR #1675 (which handles the utility/test updates).

Ready for your final approval!

**Review by wenshao — APPROVED** [review]
No issues found. LGTM! ✅ _— gpt-5.4 via Qwen Code /review_
