### PR TITLE
fix(cli): recognize OpenAI-compatible providers in `qwen auth status`

### LINKED ISSUE #3612: `qwen auth status` does not recognize OpenAI-compatible providers configured in settings.json
## Bug Description

The `qwen auth status` command only checks for two authentication methods:
- Alibaba Cloud Bailian Coding Plan
- OAuth authentication

However, it **cannot recognize OpenAI-compatible providers** configured via `~/.qwen/settings.json` under `modelProviders.openai` (such as Xunfei/iFlytek API).

## Expected Behavior

When a user configures an OpenAI-compatible provider in `~/.qwen/settings.json` like this:

```json
{
  "modelProviders": {
    "openai": {
      "baseUrl": "https://xxx/api/v1",
      "apiKey": "xxx",
      "model": "xxx"
    }
  }
}
```

And the provider works correctly (API calls succeed), `qwen auth status` should recognize this configuration and display the correct authentication status.

## Actual Behavior

`qwen auth status` still shows:
```
Alibaba Cloud Coding Plan (Incomplete)
```

This is **misleading** because the user's configuration is fully functional.

## Impact

Users who configure OpenAI-compatible providers (e.g., Xunfei API, DeepSeek, Ollama) will see an `Incomplete` status even though their setup works perfectly. This creates confusion about whether their authentication is properly configured.

## Suggested Fix

Add detection for OpenAI-compatible provider configurations in the `auth status` command logic. If `modelProviders.openai` is configured in settings.json and the API key is valid, display the appropriate status instead of falling through to the default `Alibaba Cloud Coding Plan (Incomplete)`.

## Environment

- qwen-code version: latest
- OS: Windows
- Configuration: `~/.qwen/settings.json` with `modelProviders.openai`

### PR DESCRIPTION
**Pull request by doudouOUC**
## Summary

- `qwen auth status` previously treated all `selectedType=openai` as Coding Plan, showing misleading "Alibaba Cloud Coding Plan (Incomplete)" for users with generic OpenAI-compatible providers (e.g. Xunfei, DeepSeek, Ollama)
- Split the `USE_OPENAI` branch into Coding Plan path and generic OpenAI-compatible path
- Coding Plan detected via `codingPlan.region` or `isCodingPlanConfig(baseUrl, envKey)` on the active model entry — stale env keys no longer cause misclassification
- Generic path checks API key with semantics matching `hasApiKeyForAuth()`: when explicit `envKey` exists, no fallback to `OPENAI_API_KEY`
- Generic path displays "OpenAI-compatible Provider" with model name and base URL info

Closes #3612

### Unit tests

All 17 tests pass (`vitest run src/commands/auth/status.test.ts`):

```
 ✓ src/commands/auth/status.test.ts (17 tests) 8ms

 Test Files  1 passed (1)
      Tests  17 passed (17)
```

New tests added:
- Coding Plan detected via `isCodingPlanConfig` when `codingPlan.region` is missing
- OpenAI-compatible with `OPENAI_API_KEY`
- OpenAI-compatible with custom `envKey` from `modelProviders`
- OpenAI-compatible with `settings.security.auth.apiKey`
- OpenAI-compatible incomplete (no key)
- Default model fallback when `model.name` is unset
- Explicit envKey missing + `OPENAI_API_KEY` present → Incomplete (no fallback)
- Stale Coding Plan key + active generic provider → OpenAI-compatible (not Coding Plan)

### Manual verification (tmux)

**Scenario 1: No auth configured**
```
$ HOME=/tmp/auth-test-home node packages/cli/dist/index.js auth status

=== Authentication Status ===
⚠️  No authentication method configured.
Run one of the following commands to get started:
  qwen auth qwen-oauth     - Authenticate with Qwen OAuth (free tier)
  qwen auth coding-plan      - Authenticate with Alibaba Cloud Coding Plan
Or simply run:
  qwen auth                - Interactive authentication setup
```

**Scenario 2: OpenAI-compatible provider with custom envKey (Xunfei)**

settings.json:
```json
{
  "security": { "auth": { "selectedType": "openai" } },
  "model": { "name": "spark-v4" },
  "modelProviders": {
    "openai": [{
      "id": "spark-v4",
      "envKey": "XUNFEI_API_KEY",
      "baseUrl": "https://spark-api-open.xf-yun.com/v1"
    }]
  }
}
```

```
$ XUNFEI_API_KEY=fake-key node packages/cli/dist/index.js auth status

=== Authentication Status ===
✓ Authentication Method: OpenAI-compatible Provider
  Current Model: spark-v4
  Base URL: https://spark-api-open.xf-yun.com/v1
  Status: API key configured
```

**Scenario 3: OpenAI-compatible provider without API key**
```
$ node packages/cli/dist/index.js auth status

=== Authentication Status ===
⚠️  Authentication Method: OpenAI-compatible Provider (Incomplete)
  Issue: API key not found in environment or settings
  Run `qwen auth` to re-configure.
```

**Scenario 4: Coding Plan with region and key**

settings.json:
```json
{
  "security": { "auth": { "selectedType": "openai" } },
  "codingPlan": { "region": "china", "version": "abc123def456" },
  "model": { "name": "qwen3.5-plus" }
}
```

```
$ BAILIAN_CODING_PLAN_API_KEY=fake-key node packages/cli/dist/index.js auth status

=== Authentication Status ===
✓ Authentication Method: Alibaba Cloud Coding Plan
  Region: 中国 (China) - 阿里云百炼
  Current Model: qwen3.5-plus
  Config Version: abc123de...
  Status: API key configured
```

**Scenario 5: Stale Coding Plan key + active Xunfei provider → should NOT show Coding Plan**

settings.json:
```json
{
  "security": { "auth": { "selectedType": "openai" } },
  "model": { "name": "spark-v4" },
  "modelProviders": {
    "openai": [{
      "id": "spark-v4",
      "envKey": "XUNFEI_API_KEY",
      "baseUrl": "https://spark-api-open.xf-yun.com/v1"
    }]
  }
}
```

```
$ BAILIAN_CODING_PLAN_API_KEY=stale-key XUNFEI_API_KEY=active-key node packages/cli/dist/index.js auth status

=== Authentication Status ===
✓ Authentication Method: OpenAI-compatible Provider
  Current Model: spark-v4
  Base URL: https://spark-api-open.xf-yun.com/v1
  Status: API key configured
```

**Scenario 6: Explicit envKey missing + OPENAI_API_KEY present → should NOT fallback**

```
$ OPENAI_API_KEY=fallback-key node packages/cli/dist/index.js auth status

=== Authentication Status ===
⚠️  Authentication Method: OpenAI-compatible Provider (Incomplete)
  Issue: API key not found in environment or settings
  Run `qwen auth` to re-configure.
```

**Scenario 7: Coding Plan detected via modelProviders entry (no codingPlan.region)**

settings.json:
```json
{
  "security": { "auth": { "selectedType": "openai" } },
  "model": { "name": "qwen3.5-plus" },
  "modelProviders": {
    "openai": [{
      "id": "qwen3.5-plus",
      "envKey": "BAILIAN_CODING_PLAN_API_KEY",
      "baseUrl": "https://coding.dashscope.aliyuncs.com/v1"
    }]
  }
}
```

```
$ BAILIAN_CODING_PLAN_API_KEY=real-key node packages/cli/dist/index.js auth status

=== Authentication Status ===
✓ Authentication Method: Alibaba Cloud Coding Plan
  Region: 中国 (China) - 阿里云百炼
  Current Model: qwen3.5-plus
  Status: API key configured
```
## 人工验证
image

| Scenario | Expected | Actual | Result |
|---|---|---|---|
| No auth configured | "No authentication method configured" | Same | ✅ |
| OpenAI provider + custom envKey | "OpenAI-compatible Provider" + configured | Same | ✅ |
| OpenAI provider + key missing | "OpenAI-compatible Provider (Incomplete)" | Same | ✅ |
| Coding Plan + region + key | "Alibaba Cloud Coding Plan" + region | Same | ✅ |
| Stale Coding Plan key + active Xunfei | "OpenAI-compatible Provider" (not Coding Plan) | Same | ✅ |
| Explicit envKey missing + OPENAI_API_KEY | "Incomplete" (no fallback) | Same | ✅ |
| Coding Plan via modelProviders entry | "Alibaba Cloud Coding Plan" + region | Same | ✅ |

🤖 Generated with [Qwen Code](https://github.com/QwenLM/qwen-code)

### CODE REVIEW

File: packages/cli/src/commands/auth/handler.ts [hunk 1]
```diff
@@ -446,54 +449,110 @@ export async function showAuthStatus(): Promise<void> {
...
-        );
-
-        if (codingPlanRegion) {
-          const regionDisplay =
-            codingPlanRegion === CodingPlanRegion.CHINA
-              ? t('中国 (China) - 阿里云百炼')
-              : t('Global - Alibaba Cloud');
-          writeStdoutLine(t('  Region: {{region}}', { region: regionDisplay }));
-        }
+      if (codingPlanRegion || hasCodingPlanKey) {
```
Comment (wenshao) [inline packages/cli/src/commands/auth/handler.ts]: **[Critical]** This classifies `USE_OPENAI` as Coding Plan whenever `BAILIAN_CODING_PLAN_API_KEY` is present, even if the active model/provider is a generic OpenAI-compatible provider. A stale or globally exported Coding Plan key would make `qwen auth status` show the wrong auth method and remediation instructions for users actually configured for Xunfei/DeepSeek/Ollama/etc. Please don't use the Coding Plan env var alone as the provider classifier; classify as Coding Plan only when `codingPlan.region` is present or the active resolved/modelProviders entry is identifiable as Coding Plan (for example with the already-imported `isCodingPlanConfig(...)`).

_— gpt-5.5 via Qwen Code /review_

File: packages/cli/src/commands/auth/handler.ts [hunk 2]
```diff
@@ -446,54 +449,110 @@ export async function showAuthStatus(): Promise<void> {
...
+        const modelProviders = mergedSettings.modelProviders as
+          | ModelProvidersConfig
+          | undefined;
+        const models = modelProviders?.[AuthType.USE_OPENAI];
+        const modelConfig = Array.isArray(models)
+          ? (models.find((m) => m.id === modelName) ?? models[0])
+          : undefined;
+
+        const hasApiKey =
+          !!(
```
Comment (wenshao) [inline packages/cli/src/commands/auth/handler.ts]: **[Critical]** This status check diverges from `validateAuthMethod()`: when the selected `modelProviders.openai` entry has an explicit `envKey`, validation treats that env key as authoritative and intentionally does not fall back to `OPENAI_API_KEY` or `settings.security.auth.apiKey`. Here, those fallbacks can still make status report `API key configured` even though the actual provider-specific key is missing. Please mirror the shared auth semantics: if `modelConfig?.envKey` exists, only check that key; only use default/API-key fallbacks when no explicit provider env key is configured.

_— gpt-5.5 via Qwen Code /review_

Comment (wenshao) [inline packages/cli/src/commands/auth/handler.ts]: **[Critical]** `showAuthStatus()` only inspects raw merged settings and process env, but runtime validation also accepts the resolved generation API key from `config.getModelsConfig().getGenerationConfig()?.apiKey` (which can include CLI/resolver-provided credentials). That means a valid OpenAI-compatible setup can pass auth validation/runtime but still be reported as incomplete by `qwen auth status`. Please reuse/refactor the same credential-resolution helper used by validation, or at least include the resolved generation `apiKey` in this status path.

_— gpt-5.5 via Qwen Code /review_

**Review by wenshao — CHANGES_REQUESTED** [review]

File: packages/cli/src/commands/auth/handler.ts (hunk 1 above)
Comment (doudouOUC) [reply packages/cli/src/commands/auth/handler.ts]: Fixed in b4317be.

Coding Plan detection now uses `isCodingPlanConfig(activeModelConfig?.baseUrl, activeModelConfig?.envKey)` on the active modelProviders entry, instead of checking the env var. A stale `BAILIAN_CODING_PLAN_API_KEY` in the environment no longer misclassifies a generic provider (e.g. Xunfei) as Coding Plan.

Added tmux verification: stale Coding Plan key + active Xunfei provider → correctly shows "OpenAI-compatible Provider".

File: packages/cli/src/commands/auth/handler.ts (hunk 2 above)
Comment (doudouOUC) [reply packages/cli/src/commands/auth/handler.ts]: Fixed in b4317be.

Now mirrors `hasApiKeyForAuth()` semantics (auth.ts:89-97): when `activeModelConfig?.envKey` is set, only that env var is checked — no fallback to `OPENAI_API_KEY` or `settings.security.auth.apiKey`. Fallbacks only apply when no explicit envKey is configured.

Added unit test and tmux verification: explicit envKey missing + `OPENAI_API_KEY` present → correctly shows "Incomplete".

Comment (doudouOUC) [reply packages/cli/src/commands/auth/handler.ts]: Acknowledged — this is a valid point but a pre-existing limitation, not introduced by this PR.

`showAuthStatus()` only calls `loadSettings()` and doesn't construct a full `Config` (which requires CLI args, workspace resolution, etc.). Adding `config.getModelsConfig().getGenerationConfig()?.apiKey` support would require refactoring the status command's entry point to accept or build a Config object.

Deferring to a follow-up PR to keep this change focused on the provider classification fix.

File: packages/cli/src/commands/auth/handler.ts [hunk 3]
```diff
@@ -446,54 +449,125 @@ export async function showAuthStatus(): Promise<void> {
...
+        | ModelProvidersConfig
+        | undefined;
+      const models = modelProviders?.[AuthType.USE_OPENAI];
+      const activeModelConfig = Array.isArray(models)
+        ? (models.find((m) => m.id === modelName) ??
+          (modelName ? undefined : models[0]))
+        : undefined;
+
+      // Detect Coding Plan via region OR active model matching Coding Plan baseUrl/envKey
+      const detectedCodingPlanRegion =
```
Comment (wenshao) [inline packages/cli/src/commands/auth/handler.ts]: **[Critical]** `codingPlan.region` still takes precedence over the active OpenAI provider, so stale Coding Plan metadata can keep misclassifying a generic OpenAI-compatible setup as Coding Plan. If a user previously configured Coding Plan and later switches to a generic provider without clearing the `codingPlan` block, this branch will still show `Alibaba Cloud Coding Plan` or `Coding Plan (Incomplete)` even though the active provider is generic.

```suggestion
      const providerCodingPlanRegion = isCodingPlanConfig(
        activeModelConfig?.baseUrl,
        activeModelConfig?.envKey,
      );
      const detectedCodingPlanRegion = activeModelConfig
        ? providerCodingPlanRegion
        : codingPlanRegion;
```

Please also add a regression test with `codingPlan.region` present plus an active generic `modelProviders.openai[]`, expecting `OpenAI-compatible Provider`.

_— gpt-5.5 via Qwen Code /review_

**Review by wenshao — CHANGES_REQUESTED** [review]

File: packages/cli/src/commands/auth/handler.ts (hunk 3 above)
Comment (doudouOUC) [reply packages/cli/src/commands/auth/handler.ts]: Fixed in a6581f2.

Adopted the suggested approach: when `activeModelConfig` exists, use only `isCodingPlanConfig()` result; fall back to `codingPlan.region` only when no active model config is available. Added regression test with stale `codingPlan.region` + active generic provider → correctly shows "OpenAI-compatible Provider".

File: packages/cli/src/commands/auth/handler.ts [hunk 4]
```diff
@@ -575,19 +577,34 @@ export async function showAuthStatus(): Promise<void> {
...
+        : openAiProviders[0];
+      const isActiveOpenRouter = activeModelConfig
+        ? isOpenRouterConfig(activeModelConfig)
+        : false;
+      const providerCodingPlanRegion = isCodingPlanConfig(
+        activeModelConfig?.baseUrl,
+        activeModelConfig?.envKey,
+      );
+      const detectedCodingPlanRegion = activeModelConfig
+        ? providerCodingPlanRegion
```
Comment (wenshao) [inline packages/cli/src/commands/auth/handler.ts:842]: **[Critical]** This still falls back to stale `codingPlan.region` whenever `model.name` is set but does not match any `modelProviders.openai[]` entry. In that common manual-provider case `activeModelConfig` is `undefined`, so a user with a generic OpenAI-compatible setup plus leftover Coding Plan metadata will still see Coding Plan status/remediation even though validation/runtime treats the setup as generic OpenAI-compatible. Please only use the `codingPlan.region` fallback when there is no explicit model selection/provider context, and add a regression test with `codingPlan.region` present, an unmatched `model.name`, and `OPENAI_API_KEY` or `settings.security.auth.apiKey` expecting `OpenAI-compatible Provider`.

_— gpt-5.5 via Qwen Code /review_

**Review by wenshao — CHANGES_REQUESTED** [review]

File: docs/design/tool-use-summary/tool-use-summary-design.md [hunk 5]
```diff
@@ -118,7 +118,7 @@ At T0+1s, we cannot retroactively add the label to the already-committed tool_gr
 
 This PR takes option 2 in full mode. The `tool_use_summary` entry is a real history item, rendered as a single dim `● <label>` line by `HistoryItemDisplay`. No `refreshStatic` needed.
 
-Compact mode is different because of `mergeCompactToolGroups`. When consecutive tool_groups merge, `MainContent` already calls `refreshStatic()` — that's an existing codepath, and it re-renders the merged group with the label looked up from history. So compact mode _does_ get the label as a header replacement. To avoid rendering the same label twice (once as the compact header, once as a trailing `● <label>` line), `HistoryItemDisplay` hides the standalone line when `compactMode` is true.
+Compact mode is different because of `mergeCompactToolGroups`. When consecutive tool*groups merge, `MainContent` already calls `refreshStatic()` — that's an existing codepath, and it re-renders the merged group with the label looked up from history. So compact mode \_does* get the label as a header replacement. To avoid rendering the same label twice (once as the compact header, once as a trailing `● <label>` line), `HistoryItemDisplay` hides the standalone line when `compactMode` is true.
```
Comment (wenshao) [inline docs/design/tool-use-summary/tool-use-summary-design.md:121]: **[Suggestion]** This unrelated doc line appears accidentally corrupted: `tool_groups` became `tool*groups`, and `_does_` became `\\_does*`, which makes the design doc render incorrectly and changes the identifier text. Please restore the original wording.

```suggestion
Compact mode is different because of `mergeCompactToolGroups`. When consecutive tool_groups merge, `MainContent` already calls `refreshStatic()` — that's an existing codepath, and it re-renders the merged group with the label looked up from history. So compact mode _does_ get the label as a header replacement. To avoid rendering the same label twice (once as the compact header, once as a trailing `● <label>` line), `HistoryItemDisplay` hides the standalone line when `compactMode` is true.
```

_— gpt-5.5 via Qwen Code /review_

File: packages/cli/src/commands/auth/handler.ts (hunk 4 above)
Comment (doudouOUC) [reply packages/cli/src/commands/auth/handler.ts:842]: Fixed locally.

Adjusted the fallback so stale `codingPlan` metadata is only considered when there is no explicit `model.name` selection. If `model.name` is set but does not match any `modelProviders.openai[]` entry, `qwen auth status` now stays on the generic OpenAI-compatible path instead of misclassifying as Coding Plan.

Added a regression test covering `codingPlan.region` present + unmatched `model.name`, and verified with `cd packages/cli && npx vitest run src/commands/auth/status.test.ts` plus `npm run typecheck`.

File: docs/design/tool-use-summary/tool-use-summary-design.md (hunk 5 above)
Comment (doudouOUC) [reply docs/design/tool-use-summary/tool-use-summary-design.md:121]: This one is valid, but it is unrelated to this PR and the thread is already outdated.

I am not touching `docs/design/tool-use-summary/tool-use-summary-design.md` in this auth-status fix branch, so I will leave the doc correction to the branch that introduced that text to avoid mixing unrelated changes here.

File: packages/cli/src/commands/auth/handler.ts (hunk 4 above)
Comment (doudouOUC) [reply packages/cli/src/commands/auth/handler.ts:842]: Follow-up: this is now committed and pushed in `1921d805b` (`fix(cli): avoid stale Coding Plan fallback in auth status`).

That commit updates the fallback so stale `codingPlan` metadata is ignored when `model.name` is explicitly set but unmatched, and includes the regression coverage for that case.

File: docs/design/tool-use-summary/tool-use-summary-design.md (hunk 5 above)
Comment (doudouOUC) [reply docs/design/tool-use-summary/tool-use-summary-design.md:121]: Follow-up: this auth-status fix is now committed and pushed in `1921d805b`.

The doc-thread note still stands: I did not include a docs-only correction in this PR, because that thread is unrelated to the auth-status change and already outdated.

**Review by wenshao — APPROVED** [review]
No issues found. LGTM! ✅ _— gpt-5.5 via Qwen Code /review_
