### PR TITLE
fix(core): normalize Windows PATH for MCP stdio servers

### LINKED ISSUE #3033: VS code extension doesn't work with MCP
### What happened?

In Qwen extension of vs code, I can't deal with unity MCP, although it works via `qwen-code` 

Image

as you can see, in cli it retrieved data correctly, I'd reconfigured the MCP in `Settings.json`, and restarted unity MCP.

### What did you expect to happen?

a way to specify MCP settings for extension, or deal with the same settings of `qwen-code` cli

### Client information

<details>
<summary>Client Information</summary>

Run `qwen` to enter the interactive CLI, then run the `/about` command.

```console
$ qwen /about
  │                                                                                                  │
  │ Status                                                                                           │
  │                                                                                                  │
  │ Qwen Code                         0.14.2 (f296eb1a6)                                             │
  │ Runtime                           Node.js v22.17.1 / npm 10.9.2                                  │
  │ OS                                win32 x64 (10.0.26200)                                         │
  │                                                                                                  │
  │ Auth                              Qwen OAuth                                                     │
  │ Model                             coder-model                                                    │
  │ Fast Model                        coder-model                                                    │
  │ Session ID                        ############                        │
  │ Sandbox                           no sandbox                                                     │
  │ Proxy                             no proxy                                                       │
  │ Memory Usage                      218.5 MB 
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by yiliang114**
## TLDR

Normalize Windows PATH-like environment variables before launching MCP stdio servers.

This avoids inheriting conflicting `PATH` / `Path` values from GUI-hosted environments such as the VS Code companion, which can prevent external MCP servers from starting correctly.

## Screenshots / Video Demo

N/A — no user-facing UI change. This change is limited to MCP stdio transport process environment setup in core.

## Dive Deeper

During investigation, ACP `session/new` / `session/load` were ruled out as the root cause: the CLI already loads `settings.merged.mcpServers` and only appends request-provided MCP servers.

The actual issue was in MCP stdio transport creation. On Windows, parent environments can contain both `PATH` and `Path`. Passing both through unchanged makes command resolution for child MCP processes unreliable, especially when Qwen Code is launched from GUI-hosted environments instead of a terminal.

This patch normalizes PATH-like keys into a single canonical `PATH` before constructing `StdioClientTransport`, while preserving server-specific environment overrides. It also adds a regression test covering the conflicting `PATH` / `Path` case.

## Reviewer Test Plan

1. Run:
   - `cd packages/core && npm run lint`
   - `cd packages/core && npm run typecheck`
   - `cd packages/core && npm run build`
2. Run the targeted regression test:
   - `cd packages/core && npx vitest run src/tools/mcp-client.test.ts`
3. On Windows, launch Qwen Code from a GUI-hosted environment with conflicting `PATH` / `Path` vars and confirm configured stdio MCP servers can still start.

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ✅  | ❓  | ❓  |
| npx      | ✅  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Closes #3033

### CODE REVIEW

**Review by wenshao — DISMISSED** [review]
No issues found. LGTM! ✅ _— gpt-5.4 via Qwen Code /review_

File: packages/core/src/tools/mcp-client.ts [hunk 1]
```diff
@@ -1409,13 +1476,15 @@ export async function createTransport(
       );
     }
 
+    const env = normalizePathEnvForWindows({
```
Comment (wenshao) [inline packages/core/src/tools/mcp-client.ts]: **[Critical]** This normalization changes PATH override semantics for stdio MCP servers on Windows. Because the code normalizes after merging `{ ...process.env, ...(mcpServerConfig.env || {}) }`, a server config that intentionally provides its own `PATH`/`Path` still inherits parent PATH entries instead of replacing them. That can make the child process resolve unexpected binaries from the parent environment rather than the server-configured toolchain.

A safer fix is to treat a PATH-like key in `mcpServerConfig.env` as an explicit override: normalize only the server-provided PATH-like values in that case, and only merge with `process.env` when the server config does not specify a PATH-like key.

_— gpt-5.4 via Qwen Code /review_

**Review by wenshao — CHANGES_REQUESTED** [review]

File: packages/core/src/tools/mcp-client.ts [hunk 2]
```diff
@@ -60,6 +60,73 @@ export type SendSdkMcpMessage = (
 export const MCP_DEFAULT_TIMEOUT_MSEC = 10 * 60 * 1000; // default to 10 minutes
```
Comment (wenshao) [inline packages/core/src/tools/mcp-client.ts:61]: **[Suggestion]** Duplicate code with `shellExecutionService.ts` (lines 29-103). `mergeWindowsPathValues` and `normalizePathEnvForWindows` are near-identical copies — the `shellExecutionService` version even includes fingerprint caching (`cachedWindowsPathFingerprint`/`cachedMergedWindowsPath`) that this copy omits. Two copies of the same logic create a maintenance risk: a bug fix in one could be missed in the other.

Consider extracting both functions (including caching) into a shared utility module (e.g., `src/utils/windowsPath.ts`) and importing from both locations.

_— glm-5.1 via Qwen Code /review_

File: packages/core/src/tools/mcp-client.test.ts [hunk 3]
```diff
@@ -270,6 +272,12 @@ describe('mcp-client', () => {
     });
```
Comment (wenshao) [inline packages/core/src/tools/mcp-client.test.ts:272]: **[Suggestion]** This test was retrofitted with `win32` platform mock and Windows `PATH`/`Path` env setup, but the new dedicated test "should normalize PATH-like env keys on Windows for stdio transport" (line 308) already covers that scenario fully. The retrofit is redundant and the original non-Windows command-connection coverage was lost — this test now only exercises the `win32` path.

Consider reverting this test to its original form (no platform mock, no PATH/Path setup) to restore non-Windows coverage, and keep the new dedicated test as the sole owner of Windows normalization testing.

_— glm-5.1 via Qwen Code /review_

File: packages/core/src/tools/mcp-client.ts (hunk 1 above)
Comment (yiliang114) [reply packages/core/src/tools/mcp-client.ts]: 感谢指出，确实是个关键问题。

已在 8243a183b 中修复：将 normalize 提前到 `process.env` 阶段，先合并 PATH+Path → 单一 PATH，再 spread server config env。这样 server 显式提供的 PATH 会完整替换父环境的值，而不是被错误合并。

同时新增了专门的测试用例 `should let server config PATH override parent PATH on Windows` 来验证此行为。

File: packages/core/src/tools/mcp-client.ts (hunk 2 above)
Comment (yiliang114) [reply packages/core/src/tools/mcp-client.ts:61]: 已在 8243a183b 中处理：提取 `mergeWindowsPathValues` 和 `normalizePathEnvForWindows` 到共享模块 `src/utils/windowsPath.ts`，包含 shellExecutionService 版本的 fingerprint 缓存逻辑。两处调用方均改为 import，消除重复代码。

File: packages/core/src/tools/mcp-client.test.ts (hunk 3 above)
Comment (yiliang114) [reply packages/core/src/tools/mcp-client.test.ts:272]: 已在 8243a183b 中修复：将 "should connect via command" 测试恢复为原始形式（无 platform mock，无 PATH/Path 设置），恢复非 Windows 的通用覆盖。Windows PATH normalize 由专用测试用例单独负责。

**Review by wenshao — APPROVED** [review]
No issues found. LGTM! ✅ _— gpt-5.4 via Qwen Code /review_
