### PR TITLE
fix(i18n): sync mismatched keys between en.js and zh.js

### LINKED ISSUE #3503: [i18n] 翻译文件 zh-CN.json 与 en-US.json 键不匹配
### What happened?

在比较中文（zh-CN）和英文（en-US）翻译文件时，两个文件的键（keys）存在不一致的情况下，无法完成既定对齐操作。

### What did you expect to happen?

在 zh-CN.json 中添加缺失的英文键及其对应翻译
或从 zh-CN.json 中移除多余的键
建立自动化检查机制，确保翻译文件同步更新

### Client information

Qwen Code: 0.14.5 (a6612940f)
运行环境: Node.js v22.22.1 / npm unknown
操作系统: win32 x64 (10.0.26200)
认证: API Key - openai
基础 URL: https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1
模型: qwen3.6-plus
快速模型: qwen3.6-plus
会话 ID: 7acc43af-c6e9-4b07-9fc5-819399d40e2d
沙箱: no sandbox
代理: no proxy
内存使用: 212.4 MB

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by doudouOUC**
## Summary

Fixes #3503

- Add 4 keys to `en.js` that are actively used in source code via `t()` but were missing from the canonical English locale: `Session (temporary)`, `The name of the extension to update.`, `Invalid API key...`, `Show context window usage breakdown...`
- Add 5 missing Chinese translations to `zh.js`: `No server selected`, `Value:`, `prompts`, `required`, `Enum`
- Add `npm run check-i18n` step to CI (`ci.yml` lint job) to prevent future key drift
- Skip writing `unused-keys-only-in-locales.json` in CI environments to avoid dirtying the working tree

After this change, `en.js` and `zh.js` are fully aligned at 1268 keys each.

## Test plan

- [x] `npm run check-i18n` passes with 0 errors
- [x] Verified `en.js` and `zh.js` key sets are identical (1268 keys each, 0 missing, 0 extra)
- [x] Verified `CI=true npm run check-i18n` skips JSON file write
- [x] `npm run build --workspace=packages/cli` succeeds

## 人工验证
以mcp为例
```bash
 /language ui zh-CN
```
修复前
image
修复后,显示“未选择服务器”
image

🤖 Generated with [Qwen Code](https://github.com/QwenLM/qwen-code)

---

> **📝 描述准确性更新（2026-05-31，作者自查）**
>
> 更正：键数为 1267（非 1268）。

### CODE REVIEW

File: scripts/check-i18n.ts [hunk 1]
```diff
@@ -429,15 +429,17 @@ async function main() {
...
-      const outputPath = path.join(
-        __dirname,
-        'unused-keys-only-in-locales.json',
-      );
-      saveKeysOnlyInLocalesToJson(
-        result.stats.unusedKeysOnlyInLocales,
-        outputPath,
-      );
+      // Save these keys to a JSON file (skip in CI to avoid dirtying the working tree)
+      if (!process.env.CI) {
```
Comment (wenshao) [inline scripts/check-i18n.ts]: **[Suggestion]** This new CI guard adds a typecheck error in the same touched block: `process.env` is treated as an index-signature object in this repo, so `process.env.CI` should be accessed with bracket notation. Since this PR is specifically making `check-i18n` CI-safe, it would be better to avoid introducing a fresh TS error here.

```suggestion
      if (!process.env['CI']) {
```

_— gpt-5.4 via Qwen Code /review_

Comment (doudouOUC) [reply scripts/check-i18n.ts]: Good catch\! Fixed in d8d852db6 — switched to bracket notation `process.env['CI']` to comply with `noPropertyAccessFromIndexSignature`. Thanks for the review\!

**Review by wenshao — APPROVED** [review]
No issues found. LGTM! ✅ _— gpt-5.4 via Qwen Code /review_

**Comment by doudouOUC** [comment]
hi, @pomelo-nwu @tanzhenxin  I will merge this bug fix to main branch. Feel free to reach out to me anytime if you have any further needs or concerns.
