### PR TITLE
fix(cli): prevent statusline spawn EBADF from crashing CLI (#3264)

### LINKED ISSUE #3264: ui.statusLine crashes CLI with spawn EBADF on macOS, then hits ansiRegex3 is not a function
## Summary

Enabling `ui.statusLine` causes Qwen Code CLI to crash after a normal response completes.

The assistant response succeeds, but the status line refresh immediately fails with:

```txt
Error: spawn EBADF
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at spawn (node:child_process:787:9)
    at Object.execFile (node:child_process:349:17)
    at exec (node:child_process:236:25)
    at file:///opt/homebrew/lib/node_modules/@qwen-code/qwen-code/cli.js:502641:19
    at Timeout._onTimeout (file:///opt/homebrew/lib/node_modules/@qwen-code/qwen-code/cli.js:502672:7)
    at listOnTimeout (node:internal/timers:585:17)
    at process.processTimers (node:internal/timers:521:7)
```

Then error rendering appears to hit a second issue:

```txt
TypeError: ansiRegex3 is not a function
    at module2.exports (file:///opt/homebrew/lib/node_modules/@qwen-code/qwen-code/cli.js:424225:82)
    at stringWidth (file:///opt/homebrew/lib/node_modules/@qwen-code/qwen-code/cli.js:424286:17)
    at file:///opt/homebrew/lib/node_modules/@qwen-code/qwen-code/cli.js:424335:17
    at Array.map (<anonymous>)
    at ansiAlign (file:///opt/homebrew/lib/node_modules/@qwen-code/qwen-code/cli.js:424333:19)
    at makeContentText (file:///opt/homebrew/lib/node_modules/@qwen-code/qwen-code/cli.js:511508:40)
    at boxen (file:///opt/homebrew/lib/node_modules/@qwen-code/qwen-code/cli.js:511676:10)
```

## Minimal reproduction

Use this config:

```json
{
  "ui": {
    "statusLine": {
      "type": "command",
      "command": "echo qwen-ok"
    }
  }
}
```

Run:

```bash
qwen -d -i "hello"
```

Observed:

1. Qwen starts normally
2. The prompt is processed normally
3. The assistant returns a normal response
4. Right after response completion, the CLI crashes with `spawn EBADF`

## Notes

This is not specific to a custom shell script.

I reproduced the same crash with both:

```json
"command": "echo qwen-ok"
```

and

```json
"command": "bash ~/.qwen/statusline-command.sh"
```

If I remove `ui.statusLine` entirely, the CLI works normally.

## Relevant code path

The bundled CLI appears to run the status line command here:

- `cli.js:502520`
- `cli.js:502658`
- `cli.js:502679`

It uses `child_process.exec(...)` and then writes JSON to `child.stdin`.

The secondary rendering failure appears around:

- `cli.js:424225`

## Environment

- Qwen Code: `0.14.4`
- Node.js: `v22.22.1`
- OS: macOS Darwin `25.3.0`
- Arch: `arm64`
- Terminal: Ghostty
- `TERM=xterm-ghostty`

## Expected behavior

A failing `statusLine` command should not crash the whole CLI.

At minimum, Qwen Code should ignore the status line failure and continue running.

## Workaround

Removing `ui.statusLine` from config avoids the crash completely.

## Additional observations

- The crash reproduces with a trivial status line command (`echo qwen-ok`), so it does not appear to depend on shell script complexity, `jq`, or Git.
- The main assistant response completes successfully before the crash, so the failure seems to happen specifically during the post-response status line refresh.
- Removing `ui.statusLine` makes the CLI stable again.
- This was reproduced on Node.js `v22.22.1`, so it may be related to Node 22 child process / stdio behavior on macOS.
- The terminal in use was Ghostty (`TERM=xterm-ghostty`), which may also be relevant if the issue depends on TTY handling.

### PR DESCRIPTION
**Pull request by wenshao**
## Summary

Fixes #3264.

`child_process.exec()` can throw **synchronously** for spawn errors that libuv does not report via the async `'error'` event. On macOS with Node 22, `EBADF` surfaces from `ChildProcess.spawn` (during stdio pipe setup), and the uncaught throw escapes the debounce `setTimeout` callback → `uncaughtException` → CLI crashes after every assistant response when `ui.statusLine` is configured.

Node reports a short allowlist of errors (`EACCES`, `EAGAIN`, `EMFILE`, `ENFILE`, `ENOENT`, `ENOSYS`, `EPERM`) asynchronously via `'error'`; everything else — including `EBADF` — is thrown directly from `ChildProcess.prototype.spawn`.

This PR wraps the `exec()` call in `useStatusLine` with a `try/catch` so a failing statusline degrades to no output while the rest of the CLI keeps running. The hook's generation counter already invalidates in-flight callbacks, so subsequent state changes recover normally.

## Scope and caveats

- **This fixes the symptom, not the root cause.** We don't know why `EBADF` happens on macOS Node 22 during stdio pipe setup — it may be a Node.js / libuv bug, a TTY-raw-mode race, or FD pressure from Ink's rendering. Regardless, a failing statusline command should never take the CLI down, so catching at the caller is the right layer.
- **User-visible behavior change:** on affected machines the statusline silently disappears (the error is routed to the `STATUS_LINE` debug logger, visible only with `qwen -d`). This matches the existing EPIPE handling a few lines below and is strictly better than crashing, but worth flagging.
- **Scope is intentionally narrow:** only the `useStatusLine` exec callsite is patched. Other `child_process.exec` / `spawn` call sites in the codebase may have the same sync-throw exposure — they are **not** audited by this PR. Happy to do a follow-up sweep if desired.
- **Secondary `ansiRegex3 is not a function` bug still exists.** It's an esbuild ESM/CJS interop issue in the bundled `boxen` → `string-width` → `ansi-regex` chain that fires from the error renderer. This PR prevents the path that was reaching it, so the symptom is gone, but the underlying bundling bug remains latent and will resurface for any other unhandled error that reaches `boxen`. Worth tracking in a separate issue.

## Changes

- `packages/cli/src/ui/hooks/useStatusLine.ts` — wrap `exec()` in `try/catch`; on failure log to the `STATUS_LINE` debug logger, clear output, and return. Generation counter and `activeChildRef` already handle recovery on the next state change.
- `packages/cli/src/ui/hooks/useStatusLine.test.ts` — two new tests: (1) synchronous `EBADF` throw does not crash the hook, (2) subsequent state changes recover and re-execute successfully (verifies no wedged refs).

## Test plan

- [x] `npx vitest run packages/cli/src/ui/hooks/useStatusLine.test.ts` — 32/32 pass
- [x] `npx vitest run packages/cli/src/ui/hooks/` — 635/635 pass (no regressions in neighbor hooks)
- [x] `npx tsc --noEmit -p packages/cli/tsconfig.json` — clean
- [x] `npx eslint` on modified files — clean
- [ ] Manual reproduction on macOS Node 22 with `ui.statusLine` configured (requires a macOS environment; reporter's repro steps in #3264 can be used)

### CODE REVIEW

**Review by wenshao — COMMENTED** [review]
No issues found. LGTM! ✅ _— gpt-5.4 via Qwen Code /review_

**Review by BZ-D — COMMENTED** [review]
Overall this is a well-scoped and well-documented fix. The try/catch placement is correct, tests cover both the crash and recovery paths, and the PR description is excellent. A few minor observations below (inline comments), but nothing blocking.

File: packages/cli/src/ui/hooks/useStatusLine.ts [hunk 1]
```diff
@@ -269,21 +269,33 @@ export function useStatusLine(): {
...
+          }
+        },
+      );
+    } catch (err) {
+      debugLog.error('statusline exec error:', (err as Error).message);
+      setOutput(null);
+      return;
+    }
 
     activeChildRef.current = child;
```
Comment (BZ-D) [inline packages/cli/src/ui/hooks/useStatusLine.ts:301]: nit: The generation counter has already been bumped before the try/catch (line 270). This means if exec throws, the generation is incremented but no child is created — which is harmless (stale callbacks from *previous* generations are correctly ignored), but it does mean the generation counter advances "for nothing" on every failure. Not a real problem, just noting for clarity.

Also worth considering: if exec throws repeatedly (e.g. persistent EBADF), `setOutput(null)` will be called on every debounced tick. React will bail out of the re-render since the value is already `null`, so there's no performance concern — just calling it out.

File: packages/cli/src/ui/hooks/useStatusLine.test.ts [hunk 2]
```diff
@@ -581,4 +581,57 @@ describe('useStatusLine', () => {
...
+
+  // --- Spawn failure handling (issue #3264) ---
+  //
+  // On macOS with Node 22, exec() can throw synchronously with EBADF when
+  // stdio pipe setup fails. The throw must not escape doUpdate() — or the
+  // setTimeout callback — or the whole CLI crashes.
+
+  describe('spawn failure handling', () => {
+    it('does not crash when exec throws synchronously (EBADF)', () => {
+      vi.mocked(child_process.exec).mockImplementationOnce((() => {
```
Comment (BZ-D) [inline packages/cli/src/ui/hooks/useStatusLine.test.ts:593]: nit: The `as unknown as typeof child_process.exec` cast is a bit heavy. Since `vi.mocked()` already returns the mocked type, you could use `mockImplementationOnce` with a simpler cast, or just use `vi.mocked(child_process.exec).mockImplementation(...)` and let TypeScript infer more. Minor readability preference though — not blocking.

File: packages/cli/src/ui/hooks/useStatusLine.ts (hunk 1 above)
Comment (wenshao) [reply packages/cli/src/ui/hooks/useStatusLine.ts:301]: Correct on both points. Generation advancing "for nothing" is intentional — the counter only needs to be monotonic so stale callbacks self-discard, and an extra bump on failure has no cost. And yes, repeated `setOutput(null)` when already null is a React bailout (same-value short-circuit), so no wasted renders.

File: packages/cli/src/ui/hooks/useStatusLine.test.ts (hunk 2 above)
Comment (wenshao) [reply packages/cli/src/ui/hooks/useStatusLine.test.ts:593]: The `as unknown as typeof child_process.exec` cast follows the existing pattern in this file (see beforeEach at line 103). Keeping it consistent. If we want to lighten the casts, that would be a file-wide refactor — out of scope here.

**Review by BZ-D — APPROVED** [review]
LGTM
