### PR TITLE
fix(vscode-companion): fill slash commands into input on Enter instead of auto-submitting

### LINKED ISSUE #1990: Improve Slash Command Behavior in VSCode Companion
## What would you like to be added?

Currently, when selecting a slash command from the completion menu in the VSCode Companion, the command is immediately sent to the agent. This works fine for utility commands like `/model` (switch model) and `/login` (authenticate), but is problematic for commands that communicate with the AI agent — especially custom commands that expect user input.

For example, if I have a custom command `/create-issue` that takes a task description as an argument, I have no way to provide that argument. The command is sent immediately upon selection, before I can type anything.

**Expected behavior:**

- `/model`, `/login`: Auto-submit on selection (current behavior is correct for these)
- All other commands: Place the command text in the input box so I can add arguments or context before pressing Enter

This way, selecting `/create-issue` from the menu would fill the input box with `/create-issue ` and let me type my task description before sending.

## Why is this needed?

The current auto-submit-everything behavior makes custom commands with arguments unusable in the VSCode Companion. Users must manually type the full command text instead of using the completion menu, which defeats the purpose of having autocomplete.

This is also a prerequisite for supporting future commands like `/export html` or any other command that accepts subcommands or arguments.

## Additional context

Related to the broader effort of achieving feature parity between CLI and VSCode Companion:
- #1985 (Plan Mode in VSCode Companion)

### PR DESCRIPTION
**Pull request by yiliang114**
## TLDR

- What changed: Slash commands that accept arguments (skills, custom commands) now fill into the input box when selected via Enter from the completion menu, instead of being sent immediately. No-arg built-in commands (`/clear`, `/doctor`, etc.) still auto-submit.
- Why it changed: The previous behavior made custom commands with arguments unusable from the completion menu — the command was sent before users could type anything.
- Reviewer focus: The `input` field propagation from `Session.ts` → webview `App.tsx`, and the `clientActions` refactor.

## Screenshots / Video Demo

> TODO: Add before/after recording showing completion menu behavior for skill commands vs built-in commands.

## Dive Deeper

**Protocol-level change.** `Session.ts` now populates the ACP `AvailableCommand.input` field based on the command definition: commands with `kind !== BUILT_IN` or a `completion` function get `input: { hint }`, signaling they accept arguments. Built-in commands without completion get `input: null`.

**Webview selection logic.** `App.tsx` uses the `input` field to decide behavior on Enter:
- `input` is falsy + Enter → auto-submit (no-arg commands like `/clear`)
- `input` is truthy + Enter → fill into input box (skills, commands with completion)
- Tab → always fills, unchanged
- Client-side commands (`/auth`, `/account`, `/model`) → immediate action via `clientActions` map, unchanged

**Also fixed:**
- `useMessageSubmit.ts`: `/login` → `/auth` + `/login` (legacy alias preserved)
- `useWebViewMessages.ts`: added `authCancelled` handler to clear waiting state when auth picker is dismissed
- `WebViewProvider.ts`: stale `/login` comment updated to `/auth`

## Reviewer Test Plan

1. `npm run build && npm run bundle`
2. Open the VSCode Companion extension
3. Type `/` to open the completion menu
4. **Enter on a no-arg command** (e.g. `/clear`): should execute immediately
5. **Enter on a skill** (e.g. `/commit`): should fill `/commit ` into input, cursor at end, user can type args then press Enter
6. **Tab on any command**: should always fill without submitting
7. **Select `/model`**: should open model selector immediately
8. **Select `/export`**: should fill and expand subcommand completion
9. **Type `/auth` manually and press Enter**: should trigger auth flow
10. **Cancel auth picker after triggering**: input should not be stuck in loading state

**Unit tests:**
```bash
npx vitest run packages/vscode-ide-companion/src/webview/
# 21 files, 106 tests — all pass
```

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ✅  | ⚠️  | ⚠️  |
| npx      | ⚠️  | ⚠️  | ⚠️  |
| Docker   | ⚠️  | ⚠️  | ⚠️  |
| Podman   | ⚠️  | -   | -   |
| Seatbelt | ⚠️  | -   | -   |

Testing matrix notes:
- Build + unit tests verified on macOS. Manual VSCode interaction testing pending.

## Linked issues / bugs

Resolves #1990

### CODE REVIEW

**Review by wenshao — DISMISSED** [review]
No issues found. LGTM! ✅ _— gpt-5.5 via Qwen Code /review_

**Comment by tanzhenxin** [comment]
Hi @yiliang114, this PR has been approved but currently has merge conflicts with the base branch. Could you rebase and resolve the conflicts so we can get it merged? Thanks!

File: packages/cli/src/acp-integration/session/Session.ts [hunk 1]
```diff
@@ -976,12 +977,19 @@ export class Session implements SessionContext {
...
+      // input: { hint } so the client can let users type arguments before
+      // submitting.  Built-in commands without completion get input: null so the
+      // client auto-submits them immediately on selection.
       const availableCommands: AvailableCommand[] = slashCommands.map(
         (cmd) => ({
           name: cmd.name,
           description: cmd.description,
-          input: cmd.argumentHint ? { hint: cmd.argumentHint } : null,
+          input:
+            cmd.kind !== CommandKind.BUILT_IN || cmd.completion != null
```
Comment (wenshao) [inline packages/cli/src/acp-integration/session/Session.ts]: **[Critical]** This now marks every built-in command without a completion function as `input: null`, so the webview auto-submits it on Enter. Some ACP-supported built-ins still accept meaningful arguments without exposing `completion`—for example `/bug` uses its args as the issue title and `/context detail` enables the detailed view. After this change, selecting those commands from the completion menu sends only `/<command>` immediately, preventing users from filling the arguments that the command supports. Please derive this from explicit input metadata (or preserve `argumentHint`/subcommand-aware input support for these built-ins) instead of defaulting all built-ins without completion to no-input.

_— gpt-5.5 via Qwen Code /review_

**Review by wenshao — CHANGES_REQUESTED** [review]

File: packages/vscode-ide-companion/src/webview/App.tsx [hunk 2]
```diff
@@ -796,52 +796,49 @@ export const App: React.FC = () => {
...
+          if (!serverCmd.input && !fillOnly) {
+            clearTriggerText();
+            vscode.postMessage({
+              type: 'sendMessage',
+              data: { text: `/${serverCmd.name}` },
+            });
+            closeCompletion();
+            return;
+          }
+          // Command accepts input — fall through to fill the input box.
```
Comment (wenshao) [inline packages/vscode-ide-companion/src/webview/App.tsx:842]: **[Critical]** Falling through here uses the generic insertion path, which reads `inputElement.textContent` directly. If the empty editor contains the `U+200B` height placeholder, filling a slash command can preserve that hidden character and produce text like `\u200B/commit `. `shouldSendMessage` strips the placeholder only for the emptiness check, but the actual `sendMessage` payload still uses the raw text, so downstream slash-command handling may not recognize the command.

Please normalize the text used for completion insertion, for example by stripping `U+200B` before computing `textBeforeCursor`/`newText`, and ensure the value passed to `setInputText` is placeholder-free. Be careful to adjust cursor offsets after normalization.

_— gpt-5.5 via Qwen Code /review_

**Review by wenshao — DISMISSED** [review]
Two additional critical findings from the review could not be mapped to current diff lines via GitHub's review API, so they are included here instead of inline:

- `packages/cli/src/utils/modelConfigUtils.ts`: `resolveCliGenerationConfig()` no longer includes `OPENAI_MODEL` / `QWEN_MODEL` when selecting the matching `modelProvider`; restore the OpenAI precedence `argv.model || env['OPENAI_MODEL'] || env['QWEN_MODEL'] || settings.model?.name`.
- `packages/core/src/skills/skill-manager.test.ts`: the new generic `argument-hint:` YAML mock branch returns `name: test-skill` before recognizing `name: review`, causing bundled review skill tests to fail.

_— gpt-5.5 via Qwen Code /review_

**Comment by yiliang114** [comment]
Verified locally on macOS. Built from HEAD (`407708bf6`), ran the VSCode Companion extension via F5.

**Tested cases:**

| Command | Enter behavior | Result |
|---------|---------------|--------|
| `/clear` (no-arg built-in) | auto-submit | ✅ |
| `/doctor` (no-arg built-in) | auto-submit | ✅ |
| `/bug` (built-in with argumentHint) | fills input | ✅ |
| `/context` (built-in with subCommands) | fills input | ✅ |
| `/export` (built-in with subCommands) | fills input | ✅ |
| `/commit` (skill) | fills input | ✅ |
| Tab on any command | always fills | ✅ |

No `U+200B` contamination observed in the filled text — copied the input box content to a hex editor to confirm.

Two review items from the previous round are addressed:
- `Session.ts` input-field logic: now derives `acceptsInput` from `argumentHint` and `subCommands`, not just `kind+completion` (`f92fd6a62`).
- `App.tsx` U+200B: completion insertion path now strips zero-width spaces before computing trigger position and writing back to state (`407708bf6`).

One non-blocking note: `/context` fills instead of auto-submitting because it has `subCommands`, but there's no secondary completion UI to hint the user about `detail`. Acceptable for now — works either way since bare `/context` is valid.

**Review by tanzhenxin — APPROVED** [review]
LGTM!
